# apply-paper-tuning.sh - GENERATED by scripts/gen-paper-tuning.ps1. Do not edit.
# Edit server/paper-tuning.yml and regenerate.
#
# Applies 6 managed key(s). Refuses to create a key that does not already
# exist, because Paper ignores unknown keys without any error - an invented key
# would look applied and do nothing.
#
# NOTE: YAML comments in the live files are lost, because PyYAML does not
# round-trip them. That is accepted for the same reason it is accepted for
# server.properties (D-0015): the reasons live in the repository, which is the
# source of truth, and Paper rewrites these files itself anyway. Paper will
# regenerate its own comments on the next config migration.

set -e
V=$(sudo -n ls -1 /var/lib/pelican/volumes | head -1)
D="/var/lib/pelican/volumes/$V"
OWN=999:987

echo "=== container must be stopped ==="
# Paper reads these at boot and rewrites them at shutdown, so editing a running
# server loses the edit silently - the same trap as server.properties.
if sudo -n docker ps --format '{{.Names}}' | grep -q "$V"; then
  echo "ABORT: container is running. Stop it first or the edit is discarded at shutdown."
  exit 2
fi
echo "confirmed stopped"

echo "=== backing up the config files once ==="
sudo -n mkdir -p "$D/_quarantine/config-prebuild"
for f in config/paper-global.yml config/paper-world-defaults.yml spigot.yml bukkit.yml; do
  BN=$(basename "$f")
  if sudo -n test -f "$D/$f" && ! sudo -n test -f "$D/_quarantine/config-prebuild/$BN"; then
    sudo -n cp -p "$D/$f" "$D/_quarantine/config-prebuild/$BN"
    echo "  saved $BN"
  fi
done

cat > /tmp/lt-paper-tune.py <<'LT_PY_EOF'
import sys, yaml, io

APPLY = True

# path, key, expected value
TARGETS = [
    ('config/paper-global.yml', 'spark.enabled', True),
    ('config/paper-global.yml', 'spark.enable-immediately', False),
    ('config/paper-global.yml', 'player-auto-save.rate', 5000),
    ('config/paper-global.yml', 'player-auto-save.max-per-tick', 5),
    ('spigot.yml', 'world-settings.default.ticks-per.hopper-transfer', 16),
    ('spigot.yml', 'world-settings.default.ticks-per.hopper-check', 16),
]

BASE = sys.argv[1]

def get_path(doc, parts):
    node = doc
    for p in parts:
        if not isinstance(node, dict) or p not in node:
            return (False, None)
        node = node[p]
    return (True, node)

changed_files = {}
missing = 0
drift = 0
docs = {}

for rel, key, want in TARGETS:
    full = BASE + "/" + rel
    if rel not in docs:
        with open(full, "r", encoding="utf-8") as f:
            docs[rel] = yaml.safe_load(f)
    doc = docs[rel]
    parts = key.split(".")
    exists, have = get_path(doc, parts)
    if not exists:
        # Fail closed. Paper ignores unknown keys silently, so inventing one
        # would look applied and do nothing at all.
        print("  MISSING KEY   %s :: %s  - refusing to create it" % (rel, key))
        missing += 1
        continue
    if have == want:
        print("  ok            %s :: %s = %r" % (rel, key, have))
        continue
    drift += 1
    if APPLY:
        node = doc
        for p in parts[:-1]:
            node = node[p]
        node[parts[-1]] = want
        changed_files[rel] = True
        print("  SET           %s :: %s  %r -> %r" % (rel, key, have, want))
    else:
        print("  DRIFT         %s :: %s  live=%r expected=%r" % (rel, key, have, want))

if missing:
    print("ABORT: %d managed key(s) do not exist in the live config." % missing)
    print("Paper may have renamed them. Re-derive paths with paper-config-paths.sh")
    print("and update server/paper-tuning.yml. Nothing was written.")
    sys.exit(4)

for rel in changed_files:
    full = BASE + "/" + rel
    tmp = "/tmp/lt-" + rel.replace("/", "_")
    with open(tmp, "w", encoding="utf-8") as f:
        yaml.safe_dump(docs[rel], f, default_flow_style=False, sort_keys=False, allow_unicode=True)
    print("wrote %s" % tmp)
print("FILES_TO_INSTALL=" + ",".join(changed_files.keys()))
if not changed_files:
    print("nothing to change")
LT_PY_EOF

echo "=== applying managed keys ==="
OUT=$(sudo -n python3 /tmp/lt-paper-tune.py "$D")
echo "$OUT"

FILES=$(echo "$OUT" | sed -n 's/^FILES_TO_INSTALL=//p')
if [ -z "$FILES" ]; then
  echo "no files needed changing"
else
  echo "=== installing changed files ==="
  IFS=',' ; for rel in $FILES; do
    TMP="/tmp/lt-$(echo "$rel" | tr '/' '_')"
    sudo -n cp "$TMP" "$D/$rel"
    sudo -n chown $OWN "$D/$rel"
    sudo -n chmod 644 "$D/$rel"
    sudo -n stat -c '  installed %n owner=%u:%g mode=%a size=%s' "$D/$rel"
    # sudo: python3 ran under sudo, so the temp file is root-owned, and /tmp is
    # sticky - the ubuntu user cannot remove another user's file there. Without
    # sudo this fails and set -e aborts the loop before later files install.
    sudo -n rm -f "$TMP"
  done
  unset IFS
fi
rm -f /tmp/lt-paper-tune.py
echo "PAPER TUNING APPLIED"
echo "=== END ==="
