# apply-permissions.sh - GENERATED by scripts/gen-permissions.ps1. Do not edit.
# Edit server/permissions.yml and regenerate.
#
# Builds 6 groups, 31 explicit denials on admin, and 2 test accounts.
#
# LuckPerms commands are idempotent: creating a group that exists, or setting a
# permission already set, reports "already" and changes nothing. So this is safe
# to re-run and is part of the deploy.

set -e
V=$(sudo -n ls -1 /var/lib/pelican/volumes | head -1)
D="/var/lib/pelican/volumes/$V"
CIP=$(sudo -n docker inspect "$V" --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}')

if ! sudo -n docker ps --format '{{.Names}}' | grep -q "$V"; then
  echo "ABORT: the server is not running. LuckPerms is driven through RCON, which needs a live server."
  exit 2
fi

cat > /tmp/lt-lp.py <<'LT_PY_EOF'
import socket, struct, sys, time, re
PROPS, HOST = sys.argv[1], sys.argv[2]
pw, port = None, 25575
with open(PROPS, "r", encoding="utf-8", errors="replace") as f:
    for line in f:
        if line.startswith("rcon.password="):
            pw = line.split("=", 1)[1].strip()
        elif line.startswith("rcon.port="):
            port = int(line.split("=", 1)[1].strip())
if not pw:
    print("NO_RCON_PASSWORD"); sys.exit(3)

def pkt(rid, typ, body):
    p = struct.pack("<ii", rid, typ) + body.encode("utf8") + b"\x00\x00"
    return struct.pack("<i", len(p)) + p

def rd(s):
    raw = b""
    while len(raw) < 4:
        c = s.recv(4 - len(raw))
        if not c: return ""
        raw += c
    (n,) = struct.unpack("<i", raw)
    b = b""
    while len(b) < n:
        c = s.recv(n - len(b))
        if not c: break
        b += c
    return b[8:-2].decode("utf8", errors="replace")

s = socket.create_connection((HOST, port), timeout=20)
s.settimeout(30)
s.sendall(pkt(1, 3, pw))
rd(s)

# Commands are read from stdin, one per line, so a long ladder needs one
# connection rather than one per command.
for line in sys.stdin:
    cmd = line.strip()
    if not cmd or cmd.startswith("#"):
        continue
    s.sendall(pkt(2, 2, cmd))
    out = rd(s)
    out = re.sub(r"\xa7.", "", out).strip().replace("\n", " | ")
    print("%-64s -> %s" % (cmd[:64], out[:200]))
    time.sleep(0.15)
s.close()
LT_PY_EOF

CMDS=$(mktemp)
trap 'rm -f "$CMDS" /tmp/lt-lp.py' EXIT

cat > "$CMDS" <<'LT_CMD_EOF'
# --- groups ---
lp creategroup default
lp creategroup helper
lp creategroup mod
lp creategroup srmod
lp creategroup admin
lp creategroup owner
# --- display names and weights (weight decides prefix precedence) ---
lp group default meta setdisplayname Member
lp group default meta set weight 0
lp group helper meta setdisplayname Helper
lp group helper meta set weight 10
lp group mod meta setdisplayname Mod
lp group mod meta set weight 20
lp group srmod meta setdisplayname SrMod
lp group srmod meta set weight 30
lp group admin meta setdisplayname Admin
lp group admin meta set weight 40
lp group owner meta setdisplayname Owner
lp group owner meta set weight 100
# --- inheritance ---
lp group helper parent add default
lp group mod parent add helper
lp group srmod parent add mod
lp group admin parent add srmod
lp group owner parent add admin
# --- granted nodes ---
lp group default permission set laughtail.player.basic true
lp group default permission set laughtail.rules.accept true
lp group helper permission set laughtail.staff.chat true
lp group helper permission set laughtail.report.view true
lp group helper permission set laughtail.report.claim true
lp group helper permission set laughtail.punish.mute.short true
lp group helper permission set laughtail.punish.kick true
lp group helper permission set laughtail.inspect.blocks.read true
lp group helper permission set laughtail.tp.coords true
lp group mod permission set laughtail.punish.tempban true
lp group mod permission set laughtail.punish.mute.voice true
lp group mod permission set laughtail.report.close true
lp group mod permission set laughtail.tp.player true
lp group mod permission set laughtail.inspect.inventory true
lp group srmod permission set laughtail.punish.tempban.long true
lp group srmod permission set laughtail.appeal.review true
lp group srmod permission set laughtail.punish.history true
lp group srmod permission set laughtail.punish.overturn true
lp group admin permission set laughtail.event.start true
lp group admin permission set laughtail.event.stop true
lp group admin permission set laughtail.arena.manage true
lp group admin permission set laughtail.reload true
lp group admin permission set laughtail.claims.admin true
lp group admin permission set laughtail.cosmetics.grant true
lp group admin permission set laughtail.cosmetics.revoke true
lp group admin permission set laughtail.shoptier.adjust true
lp group admin permission set laughtail.world.manage true
lp group admin permission set laughtail.rollback.preview true
lp group admin permission set laughtail.punish.permban true
lp group admin permission set chunky.base true
lp group admin permission set grim.alerts true
lp group admin permission set grim.verbose true
lp group admin permission set voicechat.admin.mute true
lp group owner permission set laughtail.economy.set true
lp group owner permission set laughtail.economy.reset true
lp group owner permission set laughtail.economy.price true
lp group owner permission set laughtail.season.reset true
lp group owner permission set laughtail.season.champion true
lp group owner permission set laughtail.backup.run true
lp group owner permission set laughtail.backup.restore true
lp group owner permission set laughtail.db.access true
lp group owner permission set laughtail.audit.read true
lp group owner permission set laughtail.secrets.read true
lp group owner permission set laughtail.whitelist.add true
lp group owner permission set laughtail.whitelist.remove true
lp group owner permission set laughtail.plugins.manage true
# --- the never-grant list, as EXPLICIT DENIALS on admin ---
# An explicit false beats an inherited true in LuckPerms, so these keep working
# even if someone later grants the node further up the chain.
lp group admin permission set * false
lp group admin permission set luckperms.* false
lp group admin permission set luckperms.user.permission.set false
lp group admin permission set luckperms.group.permission.set false
lp group admin permission set minecraft.command.op false
lp group admin permission set minecraft.command.deop false
lp group admin permission set minecraft.command.stop false
lp group admin permission set bukkit.command.stop false
lp group admin permission set minecraft.command.reload false
lp group admin permission set bukkit.command.reload false
lp group admin permission set laughtail.plugins.manage false
lp group admin permission set plugman.* false
lp group admin permission set laughtail.economy.set false
lp group admin permission set laughtail.economy.reset false
lp group admin permission set laughtail.economy.price false
lp group admin permission set coreprotect.rollback false
lp group admin permission set coreprotect.restore false
lp group admin permission set coreprotect.purge false
lp group admin permission set laughtail.backup.run false
lp group admin permission set laughtail.backup.restore false
lp group admin permission set laughtail.db.access false
lp group admin permission set laughtail.season.reset false
lp group admin permission set laughtail.season.champion false
lp group admin permission set worldedit.* false
lp group admin permission set fawe.* false
lp group admin permission set minecraft.command.whitelist false
lp group admin permission set bukkit.command.whitelist false
lp group admin permission set laughtail.whitelist.add false
lp group admin permission set laughtail.whitelist.remove false
lp group admin permission set laughtail.audit.read false
lp group admin permission set laughtail.secrets.read false
# --- test accounts for acceptance 17.5 ---
lp user 00000000-0000-4000-8000-0000000000ad parent set admin
lp user 00000000-0000-4000-8000-00000000000b parent set helper
LT_CMD_EOF

echo "=== applying $(grep -vc '^#' "$CMDS") LuckPerms commands ==="
sudo -n python3 /tmp/lt-lp.py "$D/server.properties" "$CIP" < "$CMDS"

echo "=== resulting group tree ==="
printf 'lp listgroups\n' | sudo -n python3 /tmp/lt-lp.py "$D/server.properties" "$CIP"
echo "PERMISSIONS APPLIED"
echo "=== END ==="
