# build-plugin.sh - GENERATED by scripts/gen-build-plugin.ps1. Do not edit.
# Edit the sources under plugin/ and regenerate.
#
# Builds LaughTail 0.1.0 from source, on the host, in a throwaway maven container.
#
# Nothing is installed on the host: no JDK, no Maven. Never-break rule 13 and
# 33.2 item 4 both say not to, and OA-03 means there is no snapshot to recover
# from if a host package install went wrong.

set -e

SRC=/home/ubuntu/laughtail-plugin
M2=/home/ubuntu/.m2
IMAGE=maven:3.9.9-eclipse-temurin-21
VERSION=0.1.0
V=$(sudo -n ls -1 /var/lib/pelican/volumes | head -1)
D="/var/lib/pelican/volumes/$V"
OWN=999:987

echo "=== disk before (a maven cache is not small) ==="
df -h --output=avail,pcent / | tail -1

mkdir -p "$SRC" "$M2"
# Literal path, not "$SRC/target": the guard refuses a recursive delete whose
# target is a variable, because a static check cannot know what it expands to.
# Removes only generated output, never the sources written below.
sudo -n rm -rf /home/ubuntu/laughtail-plugin/target
# Ownership: maven used to run as root in the container, which left root-owned
# output that the ubuntu user then could not clear on the next build. It now runs
# as the host user (see the docker run below), so this only matters once.
sudo -n chown -R ubuntu:ubuntu /home/ubuntu/laughtail-plugin /home/ubuntu/.m2 2>/dev/null || true
mkdir -p "$SRC/src/main/java/gg/laughtail/core" "$SRC/src/main/resources"

# ---- pom.xml ----
cat > "$SRC/pom.xml" <<'LT_SRC_EOF_pom_xml'
<?xml version="1.0" encoding="UTF-8"?>
<!--
  LaughTail core plugin.

  This is the plugin Sections 3 to 16 live inside. Everything the server does that
  is not vanilla Minecraft happens here, so it is built from source in this
  repository rather than downloaded - never-break rule 9 is about pinning third
  party jars; this one we own.

  BUILD ENVIRONMENT. Compiled inside a throwaway `maven` container on the VPS, not
  with host packages. Same reasoning as decision D-0023 for MariaDB: never-break
  rule 13 and spec 33.2 item 4 say do not install host packages mid-build without a
  snapshot, and OA-03 means no snapshot exists. A container needs nothing on the
  host and leaves nothing behind.

  JAVA 21, not 25. The server runs Temurin 25, but Paper 1.21.11 targets Java 21 and
  compiling to 21 means the jar runs on both. Targeting 25 would tie the plugin to
  this exact runtime for no benefit.

  THE MARIADB DRIVER IS SHADED IN, deliberately. Paper's plugin.yml `libraries:`
  mechanism would keep the jar small but downloads from Maven Central on first load,
  which makes startup depend on the network and makes the installed bytes something
  other than the bytes that were built. Shading is deterministic. The cost is about
  half a megabyte.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>gg.laughtail</groupId>
  <artifactId>laughtail-core</artifactId>
  <version>0.1.0</version>
  <packaging>jar</packaging>
  <name>LaughTail</name>

  <properties>
    <maven.compiler.release>21</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <!-- Pinned. Never a floating version - spec 4.2. -->
    <paper.api.version>1.21.11-R0.1-SNAPSHOT</paper.api.version>
    <mariadb.driver.version>3.5.2</mariadb.driver.version>
  </properties>

  <repositories>
    <repository>
      <id>papermc</id>
      <url>https://repo.papermc.io/repository/maven-public/</url>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>io.papermc.paper</groupId>
      <artifactId>paper-api</artifactId>
      <version>${paper.api.version}</version>
      <!-- provided: the server supplies it at runtime and it must NOT be shaded. -->
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.mariadb.jdbc</groupId>
      <artifactId>mariadb-java-client</artifactId>
      <version>${mariadb.driver.version}</version>
    </dependency>
  </dependencies>

  <build>
    <finalName>LaughTail-${project.version}</finalName>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.5.3</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals><goal>shade</goal></goals>
            <configuration>
              <createDependencyReducedPom>false</createDependencyReducedPom>
              <relocations>
                <!-- Relocated so this plugin's driver cannot collide with a driver
                     another plugin shades. Two copies of the same class in one
                     class loader is a real and confusing failure. -->
                <relocation>
                  <pattern>org.mariadb.jdbc</pattern>
                  <shadedPattern>gg.laughtail.libs.mariadb</shadedPattern>
                </relocation>
              </relocations>
              <transformers>
                <!--
                  Without this, relocation breaks JDBC discovery. The driver jar
                  ships META-INF/services/java.sql.Driver naming
                  org.mariadb.jdbc.Driver, and relocation moves the CLASS but leaves
                  that text file pointing at the old name - so DriverManager finds a
                  service entry for a class that no longer exists and reports
                  "No suitable driver found", which sounds like a connection problem
                  and is actually a packaging one.
                -->
                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
              </transformers>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                    <exclude>module-info.class</exclude>
                  </excludes>
                </filter>
              </filters>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
LT_SRC_EOF_pom_xml

# ---- src/main/resources/plugin.yml ----
cat > "$SRC/src/main/resources/plugin.yml" <<'LT_SRC_EOF_src_main_resources_plugin_yml'
name: LaughTail
version: '${project.version}'
main: gg.laughtail.core.LaughTailPlugin
api-version: '1.21'
author: LaughTail SMP
description: The LaughTail core. Access, rules gate, player registry.

# folia-supported is deliberately absent: this plugin is not Folia-safe and saying
# otherwise would let it load on a server it cannot run correctly on.

commands:
  laughtail:
    description: LaughTail administration. Never use vanilla /reload (never-break rule 7).
    usage: /laughtail <status|reload>
    aliases: [lt]
  rules:
    description: Read the rules, and accept them.
    usage: /rules [accept]

permissions:
  # These mirror server/permissions.yml. LuckPerms is the source of truth for who
  # holds them; this block only declares they exist and their default.
  #
  # Every default is 'op' or 'false', never 'true'. A permission that defaults to
  # true is granted to everyone the moment the plugin loads, which would silently
  # bypass the Section 17 ladder that was so carefully built.
  laughtail.player.basic:
    description: Baseline player access.
    default: true          # the one deliberate exception: every paying player has it
  laughtail.rules.accept:
    description: Accept the rules.
    default: true          # a new player must be able to accept, or the gate traps them
  laughtail.reload:
    description: Reload LaughTail config. 17.2 grants this to Admin; reloading the SERVER is 17.3 and denied.
    default: op
  laughtail.status:
    description: View LaughTail status including database connectivity.
    default: op
  laughtail.rules.bypass:
    description: Bypass the rules gate. Console and Owner only - never staff.
    default: false
LT_SRC_EOF_src_main_resources_plugin_yml

# ---- src/main/resources/config.yml ----
cat > "$SRC/src/main/resources/config.yml" <<'LT_SRC_EOF_src_main_resources_config_yml'
# LaughTail core configuration.
#
# THE PASSWORD IS NOT IN THIS FILE AND MUST NEVER BE. It is written into the
# deployed copy on the host by scripts/remote/deploy-plugin-config.sh, which reads
# it from /home/ubuntu/laughtail-db/secrets/app_password - root-only, never printed,
# never committed (never-break rule 5, decision D-0014's pattern).
#
# NOTE FOR ANYONE EDITING THIS FILE: do not write the placeholder token into a
# comment. An earlier version of this header quoted it, the deploy script replaced
# EVERY occurrence, and the real password was substituted into the comment and then
# printed past a redaction that only masked the "password:" line. See D-0026. The
# substitution is now anchored to the password key alone, but the cheapest defence
# is simply not to repeat the token in prose.

database:
  # 127.0.0.1 because the db container publishes only on loopback (D-0023) and the
  # game container reaches the host through the docker bridge gateway. The deploy
  # script resolves the correct address for this host rather than guessing.
  host: '__DB_HOST__'
  port: 3306
  schema: laughtail
  user: laughtail
  password: '__PRESERVE__'

rules:
  # Bump this version whenever the text changes. Every player who accepted an older
  # version is re-gated automatically - that is the entire reason acceptance row 17
  # stores a version rather than a boolean.
  #
  # '0-draft' is deliberate and honest: the real rules text is owner action OA-13,
  # which also covers Terms, Privacy and Refund wording. The GATE is built and
  # tested; the words are not mine to write.
  version: '0-draft'
  text:
    - 'These rules are a DRAFT placeholder (owner action OA-13).'
    - ''
    - '1. No cheating. No hacked clients, no exploits, no duplication.'
    - '2. No griefing outside claimed combat. Rank comes from PvP only.'
    - '3. One account per person. Alt accounts do not earn rating.'
    - '4. No real-money trading of anything in game.'
    - '5. Treat other players decently. Harassment ends access.'
    - ''
    - 'The published version of these rules will be identical on the website,'
    - 'in game and in Discord (acceptance row 18).'
LT_SRC_EOF_src_main_resources_config_yml

# ---- src/main/java/gg/laughtail/core/LaughTailPlugin.java ----
cat > "$SRC/src/main/java/gg/laughtail/core/LaughTailPlugin.java" <<'LT_SRC_EOF_src_main_java_gg_laughtail_core_LaughTailPlugin_java'
package gg.laughtail.core;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.plugin.java.JavaPlugin;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;

/**
 * LaughTail core.
 *
 * Scope at 0.1.0, deliberately small and complete rather than broad and half-done
 * (standing bias: fewer features working perfectly):
 *
 *   - registers every joining player in the database, keyed on UUID
 *   - enforces the rules gate (acceptance row 17) with the accepted VERSION stored
 *   - /laughtail status, so the server can be asked whether it is actually healthy
 *   - /laughtail reload, which is what never-break rule 7 says to use instead of
 *     vanilla /reload
 *
 * NOT here yet, and not pretended: Berries, rank, seasons, shop, cosmetics, the 6.6
 * watchdog. Those are Phases 3 to 7 and several are blocked on owner decisions
 * (Q-10 economy numbers, OA-12 price).
 */
public final class LaughTailPlugin extends JavaPlugin implements Listener {

    private Database database;
    private RulesGate rulesGate;
    private String rulesVersion;
    private List<String> rulesText;

    @Override
    public void onEnable() {
        saveDefaultConfig();
        loadSettings();

        this.rulesGate = new RulesGate(this);
        getServer().getPluginManager().registerEvents(this, this);
        getServer().getPluginManager().registerEvents(rulesGate, this);

        // Connectivity is checked ASYNCHRONOUSLY. Doing it here on the main thread
        // would block startup on a network timeout, and acceptance row 25 forbids
        // main-thread database work regardless of how convenient it is.
        getServer().getScheduler().runTaskAsynchronously(this, () -> {
            boolean ok = database.checkConnectivity();
            if (ok) {
                getLogger().info("Database reachable, migration V1 present.");
            } else {
                getLogger().severe("STARTING WITHOUT A WORKING DATABASE. "
                    + "Players will be gated and cannot be recorded. Fix the database, "
                    + "then /laughtail reload.");
            }
        });

        getLogger().info("LaughTail " + getPluginMeta().getVersion() + " enabled. Rules version "
            + rulesVersion + ".");
    }

    private void loadSettings() {
        FileConfiguration c = getConfig();
        this.rulesVersion = c.getString("rules.version", "0-draft");
        this.rulesText = c.getStringList("rules.text");
        if (rulesText.isEmpty()) {
            rulesText = List.of("The rules have not been written yet (owner action OA-13).");
        }
        this.database = new Database(
            this,
            c.getString("database.host", "127.0.0.1"),
            c.getInt("database.port", 3306),
            c.getString("database.schema", "laughtail"),
            c.getString("database.user", "laughtail"),
            c.getString("database.password", "")
        );
    }

    String rulesVersion() { return rulesVersion; }
    List<String> rulesText() { return rulesText; }

    @EventHandler
    public void onJoin(PlayerJoinEvent e) {
        Player p = e.getPlayer();

        // Gate FIRST, release later if the database says they have accepted. The
        // safe default is gated: if the database is down, a player who has already
        // accepted is inconvenienced, whereas the opposite default would let an
        // unaccepted player straight in and quietly break row 17.
        if (!p.hasPermission("laughtail.rules.bypass")) {
            rulesGate.gate(p);
        }

        getServer().getScheduler().runTaskAsynchronously(this, () -> {
            try {
                String accepted = database.registerAndGetAcceptedRules(
                    p.getUniqueId(), p.getName());
                if (rulesVersion.equals(accepted)) {
                    getServer().getScheduler().runTask(this, () -> {
                        if (p.isOnline()) {
                            rulesGate.release(p);
                            p.sendMessage(Component.text("Welcome back to Laugh Tale.", NamedTextColor.GOLD));
                        }
                    });
                } else if (accepted != null) {
                    // Accepted an OLDER version. This is precisely why row 17 wants
                    // the version stored rather than a boolean.
                    getServer().getScheduler().runTask(this, () -> {
                        if (p.isOnline()) {
                            p.sendMessage(Component.text(
                                "The rules have changed since you last accepted them.",
                                NamedTextColor.YELLOW));
                        }
                    });
                }
            } catch (SQLException ex) {
                getLogger().log(Level.SEVERE,
                    "Could not record player " + p.getUniqueId() + ": " + ex.getMessage());
                getServer().getScheduler().runTask(this, () -> {
                    if (p.isOnline()) {
                        p.sendMessage(Component.text(
                            "The server could not reach its database. Staff have been notified.",
                            NamedTextColor.RED));
                    }
                });
            }
        });
    }

    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        String name = cmd.getName().toLowerCase();

        if (name.equals("rules")) {
            if (!(sender instanceof Player p)) {
                sender.sendMessage("Rules version " + rulesVersion);
                return true;
            }
            if (args.length == 0) {
                rulesGate.showRules(p);
                return true;
            }
            if (args[0].equalsIgnoreCase("accept")) {
                if (!p.hasPermission("laughtail.rules.accept")) {
                    p.sendMessage(Component.text("You cannot accept the rules.", NamedTextColor.RED));
                    return true;
                }
                if (!rulesGate.isGated(p)) {
                    p.sendMessage(Component.text("You have already accepted the current rules.",
                        NamedTextColor.GRAY));
                    return true;
                }
                final String version = rulesVersion;
                getServer().getScheduler().runTaskAsynchronously(this, () -> {
                    try {
                        database.recordRulesAcceptance(p.getUniqueId(), version);
                        getServer().getScheduler().runTask(this, () -> {
                            if (p.isOnline()) {
                                rulesGate.release(p);
                                p.sendMessage(Component.text(
                                    "Rules accepted (version " + version + "). Welcome to Laugh Tale.",
                                    NamedTextColor.GREEN));
                            }
                        });
                    } catch (SQLException ex) {
                        getLogger().log(Level.SEVERE, "Could not store rules acceptance: " + ex.getMessage());
                        getServer().getScheduler().runTask(this, () -> {
                            if (p.isOnline()) {
                                // NOT released. An acceptance that was not stored did
                                // not happen - releasing anyway would make row 17 a lie.
                                p.sendMessage(Component.text(
                                    "Could not save your acceptance. Please try again.",
                                    NamedTextColor.RED));
                            }
                        });
                    }
                });
                return true;
            }
            p.sendMessage(Component.text("Usage: /rules [accept]", NamedTextColor.GRAY));
            return true;
        }

        if (name.equals("laughtail")) {
            if (args.length == 0 || args[0].equalsIgnoreCase("status")) {
                if (!sender.hasPermission("laughtail.status")) {
                    sender.sendMessage(Component.text("No permission.", NamedTextColor.RED));
                    return true;
                }
                sender.sendMessage(Component.text("LaughTail " + getPluginMeta().getVersion(),
                    NamedTextColor.GOLD));
                sender.sendMessage(Component.text("  rules version: " + rulesVersion, NamedTextColor.GRAY));
                sender.sendMessage(Component.text("  database: "
                    + (database.isHealthy() ? "reachable" : "NOT REACHABLE"),
                    database.isHealthy() ? NamedTextColor.GREEN : NamedTextColor.RED));
                getServer().getScheduler().runTaskAsynchronously(this, () -> {
                    String line;
                    try {
                        line = "  players recorded: " + database.countPlayers();
                    } catch (SQLException ex) {
                        line = "  players recorded: query failed - " + ex.getMessage();
                    }
                    final String out = line;
                    getServer().getScheduler().runTask(this, () ->
                        sender.sendMessage(Component.text(out, NamedTextColor.GRAY)));
                });
                return true;
            }
            if (args[0].equalsIgnoreCase("reload")) {
                if (!sender.hasPermission("laughtail.reload")) {
                    sender.sendMessage(Component.text("No permission.", NamedTextColor.RED));
                    return true;
                }
                reloadConfig();
                loadSettings();
                getServer().getScheduler().runTaskAsynchronously(this, () -> database.checkConnectivity());
                sender.sendMessage(Component.text(
                    "LaughTail config reloaded. Rules version " + rulesVersion + ".",
                    NamedTextColor.GREEN));
                sender.sendMessage(Component.text(
                    "This is the reload to use - never vanilla /reload (never-break rule 7).",
                    NamedTextColor.DARK_GRAY));
                return true;
            }
            sender.sendMessage(Component.text("Usage: /laughtail <status|reload>", NamedTextColor.GRAY));
            return true;
        }
        return false;
    }
}
LT_SRC_EOF_src_main_java_gg_laughtail_core_LaughTailPlugin_java

# ---- src/main/java/gg/laughtail/core/Database.java ----
cat > "$SRC/src/main/java/gg/laughtail/core/Database.java" <<'LT_SRC_EOF_src_main_java_gg_laughtail_core_Database_java'
package gg.laughtail.core;

import org.bukkit.plugin.Plugin;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.UUID;
import java.util.logging.Level;

/**
 * The database layer.
 *
 * ACCEPTANCE ROW 25 IS THE DESIGN CONSTRAINT: no database call on the main thread.
 * A query that takes 50 ms on the main thread is a 50 ms tick, and the whole tick
 * budget is 25 ms. So every method here refuses to run on the main thread and says
 * so loudly rather than quietly costing tick time - Law 8, fail loud not slow.
 *
 * Connections are opened per operation rather than pooled. That is a deliberate
 * choice for this stage: a pool is the right answer under load, but pooling adds a
 * dependency and configuration surface for a server with at most 24 players whose
 * writes are a handful per join. This will need revisiting before Phase 3's order
 * book, which is write-heavy and latency-sensitive - noted rather than pretended
 * away.
 */
public final class Database {

    private final Plugin plugin;
    private final String url;
    private final String user;
    private final String password;
    private volatile boolean healthy;

    Database(Plugin plugin, String host, int port, String schema, String user, String password) {
        this.plugin = plugin;
        // useServerPrepStmts: real prepared statements server-side. Every query in
        // this class is parameterised - string-concatenated SQL is how player data
        // gets stolen, and a player name is attacker-controlled input.
        this.url = "jdbc:mariadb://" + host + ":" + port + "/" + schema
                + "?useServerPrepStmts=true&connectTimeout=5000&socketTimeout=15000";
        this.user = user;
        this.password = password;
    }

    private void assertOffMainThread() {
        if (plugin.getServer().isPrimaryThread()) {
            throw new IllegalStateException(
                "LaughTail: refusing a database call on the main thread (acceptance row 25). "
              + "Wrap it in runTaskAsynchronously.");
        }
    }

    private Connection open() throws SQLException {
        // The driver is instantiated DIRECTLY rather than going through
        // DriverManager's ServiceLoader discovery.
        //
        // Why: this jar relocates org.mariadb.jdbc to gg.laughtail.libs.mariadb so it
        // cannot collide with a driver another plugin shades. Relocation rewrites the
        // classes but not, by default, the META-INF/services text file that names the
        // driver - so DriverManager looked up a class that no longer existed and
        // reported "No suitable driver found", which reads like a network fault and is
        // actually a packaging one. The build now also relocates the service file, but
        // referring to the type directly means correctness does not depend on that at
        // all: Maven Shade rewrites this reference at the bytecode level, so it is
        // right by construction.
        java.util.Properties props = new java.util.Properties();
        props.setProperty("user", user);
        props.setProperty("password", password);
        Connection c = new org.mariadb.jdbc.Driver().connect(url, props);
        if (c == null) {
            throw new SQLException("MariaDB driver declined the URL: " + url);
        }
        return c;
    }

    /** Verifies connectivity and that the migration the plugin expects has been applied. */
    boolean checkConnectivity() {
        assertOffMainThread();
        try (Connection c = open();
             PreparedStatement ps = c.prepareStatement(
                 "SELECT COUNT(*) FROM schema_migrations WHERE version = ?")) {
            ps.setString(1, "V1");
            try (ResultSet rs = ps.executeQuery()) {
                boolean ok = rs.next() && rs.getInt(1) == 1;
                healthy = ok;
                if (!ok) {
                    plugin.getLogger().severe(
                        "Database reachable but migration V1 is NOT applied. Run db-migrate.sh. "
                      + "Refusing to pretend the schema is present.");
                }
                return ok;
            }
        } catch (SQLException e) {
            healthy = false;
            plugin.getLogger().log(Level.SEVERE, "Database unreachable: " + e.getMessage());
            return false;
        }
    }

    boolean isHealthy() {
        return healthy;
    }

    /**
     * Records a player on join and returns the rules version they have accepted,
     * or null if they have accepted nothing.
     *
     * Upsert on UUID, never on name: Appendix D's rule, and names are reusable -
     * the owner's own account was renamed from dipanshu03j to IgnisClaw (D-0017),
     * which is exactly the case that breaks name-keyed storage.
     */
    String registerAndGetAcceptedRules(UUID uuid, String name) throws SQLException {
        assertOffMainThread();
        try (Connection c = open()) {
            try (PreparedStatement ps = c.prepareStatement(
                    "INSERT INTO players (uuid, current_name, first_join, last_seen, created_at, updated_at) "
                  + "VALUES (?, ?, UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), UTC_TIMESTAMP(3)) "
                  + "ON DUPLICATE KEY UPDATE current_name = VALUES(current_name), "
                  + "last_seen = UTC_TIMESTAMP(3), updated_at = UTC_TIMESTAMP(3)")) {
                ps.setString(1, uuid.toString());
                ps.setString(2, name);
                ps.executeUpdate();
            }
            try (PreparedStatement ps = c.prepareStatement(
                    "SELECT rules_version_accepted FROM players WHERE uuid = ?")) {
                ps.setString(1, uuid.toString());
                try (ResultSet rs = ps.executeQuery()) {
                    return rs.next() ? rs.getString(1) : null;
                }
            }
        }
    }

    /**
     * Stores rules acceptance WITH THE VERSION, which is what acceptance row 17
     * requires - not a boolean. A boolean cannot re-gate everyone when the rules
     * change, and the rules will change.
     */
    void recordRulesAcceptance(UUID uuid, String version) throws SQLException {
        assertOffMainThread();
        try (Connection c = open();
             PreparedStatement ps = c.prepareStatement(
                 "UPDATE players SET rules_version_accepted = ?, rules_accepted_at = UTC_TIMESTAMP(3), "
               + "updated_at = UTC_TIMESTAMP(3) WHERE uuid = ?")) {
            ps.setString(1, version);
            ps.setString(2, uuid.toString());
            ps.executeUpdate();
        }
    }

    /** Player count, for /laughtail status. */
    int countPlayers() throws SQLException {
        assertOffMainThread();
        try (Connection c = open();
             PreparedStatement ps = c.prepareStatement("SELECT COUNT(*) FROM players");
             ResultSet rs = ps.executeQuery()) {
            return rs.next() ? rs.getInt(1) : -1;
        }
    }
}
LT_SRC_EOF_src_main_java_gg_laughtail_core_Database_java

# ---- src/main/java/gg/laughtail/core/RulesGate.java ----
cat > "$SRC/src/main/java/gg/laughtail/core/RulesGate.java" <<'LT_SRC_EOF_src_main_java_gg_laughtail_core_RulesGate_java'
package gg.laughtail.core;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.event.entity.EntityDamageByEntityEvent;
import org.bukkit.event.inventory.InventoryOpenEvent;
import org.bukkit.event.player.AsyncPlayerChatEvent;
import org.bukkit.event.player.PlayerCommandPreprocessEvent;
import org.bukkit.event.player.PlayerDropItemEvent;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.event.player.PlayerMoveEvent;
import org.bukkit.event.player.PlayerQuitEvent;

import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

/**
 * The rules gate. Acceptance row 17: "A new player cannot move, build or chat
 * before accepting; acceptance is stored with a version."
 *
 * WHY EACH EVENT IS BLOCKED. Row 17 names move, build and chat. Blocking only those
 * three would leave a gated player able to open chests, drop items, hit other
 * players and run commands - so the gate would be theatre. What is blocked here is
 * everything that changes the world or interacts with anyone, and nothing else.
 *
 * WHAT IS DELIBERATELY NOT BLOCKED: looking around. PlayerMoveEvent fires for
 * head rotation as well as position, so cancelling every move would freeze the
 * camera and feel like a crash rather than a gate. Only actual position changes are
 * cancelled - the player can look around and read, which is the point.
 *
 * The allowed command list is minimal and explicit. A gated player must be able to
 * accept the rules and read them; everything else waits.
 */
public final class RulesGate implements Listener {

    private final LaughTailPlugin plugin;
    private final Set<UUID> gated = ConcurrentHashMap.newKeySet();

    private static final Set<String> ALLOWED_COMMANDS = Set.of(
        "/rules", "/rules accept", "/help"
    );

    RulesGate(LaughTailPlugin plugin) {
        this.plugin = plugin;
    }

    void gate(Player p) {
        gated.add(p.getUniqueId());
        showRules(p);
    }

    void release(Player p) {
        gated.remove(p.getUniqueId());
    }

    boolean isGated(Player p) {
        return gated.contains(p.getUniqueId());
    }

    void showRules(Player p) {
        p.sendMessage(Component.text("â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€", NamedTextColor.DARK_GRAY));
        p.sendMessage(Component.text("LAUGH TALE â€” the rules", NamedTextColor.GOLD));
        p.sendMessage(Component.empty());
        for (String line : plugin.rulesText()) {
            p.sendMessage(Component.text("  " + line, NamedTextColor.GRAY));
        }
        p.sendMessage(Component.empty());
        p.sendMessage(Component.text("  Type ", NamedTextColor.YELLOW)
            .append(Component.text("/rules accept", NamedTextColor.GREEN))
            .append(Component.text(" to continue.", NamedTextColor.YELLOW)));
        p.sendMessage(Component.text("  You cannot move, build or chat until you do.", NamedTextColor.DARK_GRAY));
        p.sendMessage(Component.text("â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€", NamedTextColor.DARK_GRAY));
    }

    private void deny(Player p) {
        p.sendActionBar(Component.text("Accept the rules first: /rules accept", NamedTextColor.RED));
    }

    // Position changes only. Head rotation is allowed on purpose - see the class note.
    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void onMove(PlayerMoveEvent e) {
        if (!isGated(e.getPlayer())) return;
        if (e.getFrom().getX() == e.getTo().getX()
         && e.getFrom().getY() == e.getTo().getY()
         && e.getFrom().getZ() == e.getTo().getZ()) {
            return;
        }
        e.setCancelled(true);
    }

    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void onBreak(BlockBreakEvent e) {
        if (isGated(e.getPlayer())) { e.setCancelled(true); deny(e.getPlayer()); }
    }

    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void onPlace(BlockPlaceEvent e) {
        if (isGated(e.getPlayer())) { e.setCancelled(true); deny(e.getPlayer()); }
    }

    @SuppressWarnings("deprecation") // AsyncPlayerChatEvent: Paper's replacement is not on the 1.21 API surface uniformly
    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void onChat(AsyncPlayerChatEvent e) {
        if (isGated(e.getPlayer())) { e.setCancelled(true); deny(e.getPlayer()); }
    }

    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void onInteract(PlayerInteractEvent e) {
        if (isGated(e.getPlayer())) { e.setCancelled(true); }
    }

    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void onInventory(InventoryOpenEvent e) {
        if (e.getPlayer() instanceof Player p && isGated(p)) { e.setCancelled(true); deny(p); }
    }

    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void onDrop(PlayerDropItemEvent e) {
        if (isGated(e.getPlayer())) { e.setCancelled(true); }
    }

    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void onDamage(EntityDamageByEntityEvent e) {
        if (e.getDamager() instanceof Player p && isGated(p)) { e.setCancelled(true); deny(p); }
    }

    @EventHandler(priority = EventPriority.LOWEST, ignoreCancelled = true)
    public void onCommand(PlayerCommandPreprocessEvent e) {
        if (!isGated(e.getPlayer())) return;
        String msg = e.getMessage().toLowerCase().trim();
        for (String allowed : ALLOWED_COMMANDS) {
            if (msg.equals(allowed) || msg.startsWith(allowed + " ")) return;
        }
        e.setCancelled(true);
        deny(e.getPlayer());
    }

    @EventHandler
    public void onQuit(PlayerQuitEvent e) {
        // Do not leak UUIDs for players who left mid-gate.
        gated.remove(e.getPlayer().getUniqueId());
    }
}
LT_SRC_EOF_src_main_java_gg_laughtail_core_RulesGate_java

echo "=== source staged ==="
find "$SRC/src" "$SRC/pom.xml" -type f | sort | while read -r f; do
  echo "  $(wc -l < "$f" | tr -d " ") lines  ${f#$SRC/}"
done

echo "=== is the image present, and is it the right architecture? ==="
sudo -n docker pull "$IMAGE" 2>&1 | tail -2
sudo -n docker inspect "$IMAGE" --format 'arch={{.Architecture}}'

echo "=== compiling ==="
# --memory 640m: this box has roughly 300 MB spare with the server running
# (baselines.md B3), so an unbounded maven JVM could push the host into OOM and
# take the game server with it. Capped deliberately, and the cap is generous
# enough for a six-file project.
#
# The .m2 cache is mounted so a rebuild does not re-download the world - the
# first build fetches Paper API and the MariaDB driver, later ones do not.
set +e
sudo -n docker run --rm \
  --memory 640m --memory-swap 640m \
  --cpus 1.5 \
  -u "$(id -u ubuntu):$(id -g ubuntu)" \
  -e HOME=/var/maven \
  -e MAVEN_CONFIG=/var/maven/.m2 \
  -v "$SRC":/src \
  -v "$M2":/var/maven/.m2 \
  -w /src \
  "$IMAGE" mvn -B -q -DskipTests -Dmaven.repo.local=/var/maven/.m2/repository package 2>&1 | tail -30
RC=${PIPESTATUS[0]}
set -e
echo "maven exit: $RC"
if [ "$RC" -ne 0 ]; then
  echo "BUILD FAILED - installing nothing."
  exit 3
fi

JAR="$SRC/target/LaughTail-$VERSION.jar"
if [ ! -s "$JAR" ]; then
  echo "BUILD REPORTED SUCCESS BUT THERE IS NO JAR - refusing to continue."
  ls -la "$SRC/target" 2>/dev/null | head
  exit 4
fi
echo "=== built ==="
ls -l "$JAR" | sed 's/^/  /'
sha256sum "$JAR" | sed 's/^/  /'

echo "=== the jar must contain the plugin descriptor and the shaded driver ==="
# `jar tf`, not `unzip -l`: the maven image ships a JDK but no unzip, and the
# first version of this check died on that after a successful build.
sudo -n docker run --rm -v "$SRC":/src -w /src "$IMAGE" \
  sh -c "jar tf target/LaughTail-$VERSION.jar | grep -E '^plugin.yml$|^config.yml$|LaughTailPlugin.class|RulesGate.class|Database.class|gg/laughtail/libs/mariadb/' | head -8"
echo "--- driver classes shaded and relocated: ---"
sudo -n docker run --rm -v "$SRC":/src -w /src "$IMAGE" \
  sh -c "jar tf target/LaughTail-$VERSION.jar | grep -c '^gg/laughtail/libs/mariadb/'"
echo "--- and NO unrelocated org/mariadb (0 expected, or the relocation silently failed): ---"
sudo -n docker run --rm -v "$SRC":/src -w /src "$IMAGE" \
  sh -c "jar tf target/LaughTail-$VERSION.jar | grep -c '^org/mariadb/' || true"

echo "=== installing into the server ==="
# The old jar is replaced, not left beside the new one - two versions of the
# same plugin in plugins/ is a load-order coin toss.
sudo -n rm -f "$D/plugins"/LaughTail-*.jar
sudo -n cp "$JAR" "$D/plugins/LaughTail-$VERSION.jar"
sudo -n chown $OWN "$D/plugins/LaughTail-$VERSION.jar"
sudo -n chmod 644 "$D/plugins/LaughTail-$VERSION.jar"
sudo -n ls -l "$D/plugins" | grep -i laughtail | sed 's/^/  /'

echo "=== disk after ==="
df -h --output=avail,pcent / | tail -1
sudo -n du -sh "$M2" 2>/dev/null | sed 's/^/  maven cache /'
echo "PLUGIN BUILT AND INSTALLED"
echo "=== END ==="
