# check-paper-drift.sh - GENERATED by scripts/gen-paper-tuning.ps1. READ ONLY.
#
# Reports whether the managed Paper keys still match the repository. Checks ONLY
# those keys - Paper owns everything else, and comparing whole files would report
# drift on every boot and config migration (see D-0015).
#
# Safe to run while the server is up: it reads and never writes.

V=$(sudo -n ls -1 /var/lib/pelican/volumes | head -1)
D="/var/lib/pelican/volumes/$V"

cat > /tmp/lt-paper-drift.py <<'LT_PY_EOF'
import sys, yaml, io

APPLY = False

# path, key, expected value
TARGETS = [
    ('config/paper-global.yml', 'spark.enabled', True),
    ('config/paper-global.yml', 'spark.enable-immediately', False),
    ('config/paper-global.yml', 'player-auto-save.rate', 5000),
    ('config/paper-global.yml', 'player-auto-save.max-per-tick', 5),
    ('spigot.yml', 'world-settings.default.ticks-per.hopper-transfer', 16),
    ('spigot.yml', 'world-settings.default.ticks-per.hopper-check', 16),
]

BASE = sys.argv[1]

def get_path(doc, parts):
    node = doc
    for p in parts:
        if not isinstance(node, dict) or p not in node:
            return (False, None)
        node = node[p]
    return (True, node)

changed_files = {}
missing = 0
drift = 0
docs = {}

for rel, key, want in TARGETS:
    full = BASE + "/" + rel
    if rel not in docs:
        with open(full, "r", encoding="utf-8") as f:
            docs[rel] = yaml.safe_load(f)
    doc = docs[rel]
    parts = key.split(".")
    exists, have = get_path(doc, parts)
    if not exists:
        # Fail closed. Paper ignores unknown keys silently, so inventing one
        # would look applied and do nothing at all.
        print("  MISSING KEY   %s :: %s  - refusing to create it" % (rel, key))
        missing += 1
        continue
    if have == want:
        print("  ok            %s :: %s = %r" % (rel, key, have))
        continue
    drift += 1
    if APPLY:
        node = doc
        for p in parts[:-1]:
            node = node[p]
        node[parts[-1]] = want
        changed_files[rel] = True
        print("  SET           %s :: %s  %r -> %r" % (rel, key, have, want))
    else:
        print("  DRIFT         %s :: %s  live=%r expected=%r" % (rel, key, have, want))

if missing:
    print("ABORT: %d managed key(s) do not exist in the live config." % missing)
    print("Paper may have renamed them. Re-derive paths with paper-config-paths.sh")
    print("and update server/paper-tuning.yml. Nothing was written.")
    sys.exit(4)

print("drift=%d" % drift)
sys.exit(1 if drift else 0)
LT_PY_EOF

echo "=== managed Paper keys vs the repository ==="
sudo -n python3 /tmp/lt-paper-drift.py "$D"
RC=$?
rm -f /tmp/lt-paper-drift.py
if [ "$RC" -eq 0 ]; then echo "NO DRIFT"; else echo "DRIFT PRESENT (exit $RC)"; fi
echo "=== END ==="
exit $RC
