# db-migrate.sh - GENERATED by scripts/gen-db-migrate.ps1. Do not edit by hand.
# Edit db/migrations/*.sql and regenerate.
# Carries 5 migration(s): V1__init.sql, V2__combat_stats_and_moderation.sql, V3__economy.sql, V4__homes_and_teleports.sql, V5__market.sql
#
# Applies pending migrations in version order and records a SHA-256 of each file
# as applied.
#
# FORWARD-ONLY IS ENFORCED, NOT REQUESTED. If an already-applied migration has a
# different checksum now, the run ABORTS and applies nothing. Appendix D says
# never modify a live schema by hand; the corollary is never modify an applied
# migration, because the database cannot be re-derived from it afterwards. Without
# a checksum an edited V1 is indistinguishable from an untouched one.
#
# Runs as the APP user, not root: full rights on the laughtail database and none
# outside it, so a mistake in a migration cannot reach the Panel data or the mysql
# system tables. Passwords are read inside the container and never printed.

set -e

NAME=laughtail-db
DB=laughtail
WORK=/home/ubuntu/laughtail-db/migrations

if ! sudo -n docker ps --format '{{.Names}}' | grep -qx "$NAME"; then
  echo "ABORT: the $NAME container is not running. Start it with db-up.sh."
  exit 2
fi

sudo -n mkdir -p "$WORK"

# Helper: run SQL as the app user. Password never appears in argv or output.
#
# The output is captured and filtered with sed, NOT piped through grep. Piping to
# grep makes the pipeline exit status grep's: a statement like CREATE TABLE
# produces no output, grep finds nothing, exits 1, and under set -e the whole run
# aborts on a statement that actually succeeded. The real mariadb exit status has
# to survive, because the row 36 test depends on distinguishing success from a
# constraint violation.
q() {
  local out rc
  out=$(sudo -n docker exec -u root "$NAME" sh -c "mariadb -u $DB -p\"\$(cat /run/lt-secrets/app_password)\" -D $DB -N -B -e \"$1\"" 2>&1)
  rc=$?
  printf '%s\n' "$out" | sed '/password on the command line/d'
  return $rc
}

# Helper: run a whole file as the app user.
qfile() {
  local out rc
  out=$(sudo -n docker exec -i -u root "$NAME" sh -c "mariadb -u $DB -p\"\$(cat /run/lt-secrets/app_password)\" -D $DB" < "$1" 2>&1)
  rc=$?
  printf '%s\n' "$out" | sed '/password on the command line/d'
  return $rc
}

echo "=== connectivity ==="
q "SELECT VERSION() AS version, DATABASE() AS db, @@time_zone AS tz;"

# ---- stage V1__init.sql ----
sudo -n tee "$WORK/V1__init.sql" > /dev/null <<'LT_SQL_EOF_V1__init_sql'
-- V1__init.sql - LaughTail SMP initial schema
--
-- Appendix D: "Use schema migrations from the first commit. Never modify a live
-- schema by hand." Spec 5.2 names MariaDB. This file is FORWARD-ONLY: once it has
-- been applied anywhere, it is never edited. Corrections arrive as V2, V3, ...
-- scripts/remote/db-migrate.sh enforces that with a checksum.
--
-- SCOPE. This migration deliberately does NOT create all 23 Appendix D tables.
-- It creates the migration bookkeeping, the two tables Phase 0 and Phase 1 need,
-- and the season/champion pair. Each later phase adds its own tables in its own
-- migration, which is what forward-only migrations are for and what keeps the
-- schema reviewable. The economy tables in particular should not be guessed at
-- now: questions.md Q-10 records that the economy has no numbers anywhere in the
-- specification, and schema written against undecided mechanics gets rewritten.
--
-- The one exception is `champions`, created here even though seasons are Phase 4.
-- Acceptance row 36 requires "exactly one Champion per season" to be proven with
-- "schema plus failed-insert test" - a DATABASE CONSTRAINT, not application logic.
-- So the constraint is a Phase 0 artefact by the acceptance table's own wording.
--
-- CONVENTIONS, and why each was chosen:
--
-- UUIDs are CHAR(36) with an ascii_bin collation, not BINARY(16). BINARY(16) is
-- more compact and is the usual advice, but this server holds tens of players, not
-- millions, so the space saving is irrelevant while the debugging cost is real -
-- every manual query, every log line and every support conversation would need
-- hex conversion. ascii_bin gives exact, case-sensitive matching with no
-- collation surprises. Appendix D's rule is that tables key on UUID and never on
-- name; both representations satisfy it.
--
-- Timestamps are DATETIME(3), not TIMESTAMP. TIMESTAMP is stored as a 32-bit
-- offset and dies in 2038, and MariaDB silently converts it using the session
-- time zone, which means the same row reads differently from two connections.
-- Every value here is UTC by convention, stated in each column comment. 31.1 puts
-- the season reset on a clock, so an ambiguous instant is a real bug.
--
-- Money is BIGINT, never a float. Berries are integers; a floating-point balance
-- cannot be summed reliably and would break the arbitrage audit in Phase 3.
--
-- Engine is InnoDB throughout, because Appendix D requires that "every write that
-- spans two tables runs in a transaction" and only InnoDB gives that.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- ---------------------------------------------------------------------------
-- schema_migrations - what has been applied, and proof it has not been edited
-- ---------------------------------------------------------------------------
-- Retention: permanent. One row per migration, forever. It is the audit trail.
CREATE TABLE IF NOT EXISTS schema_migrations (
  version        VARCHAR(20)   NOT NULL COMMENT 'V1, V2, ... sorts by numeric part',
  description    VARCHAR(200)  NOT NULL,
  checksum       CHAR(64)      NOT NULL COMMENT 'SHA-256 of the file as applied; a mismatch means someone edited an applied migration',
  applied_at     DATETIME(3)   NOT NULL COMMENT 'UTC',
  applied_by     VARCHAR(100)  NOT NULL COMMENT 'who or what ran it',
  duration_ms    INT UNSIGNED  NOT NULL,
  PRIMARY KEY (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- players - one row per human, keyed on Mojang UUID
-- ---------------------------------------------------------------------------
-- Retention: permanent while access exists. 31.13 governs deletion on request;
-- a deletion anonymises this row rather than removing it, so that transaction and
-- punishment history stays referentially intact.
CREATE TABLE IF NOT EXISTS players (
  uuid                   CHAR(36)     NOT NULL COMMENT 'Mojang UUID, dashed lowercase. Version 4 only: an offline-mode v3 UUID must never appear here (decision D-0017)',
  current_name           VARCHAR(16)  NOT NULL COMMENT 'Minecraft names are at most 16 chars. Cached for display ONLY - never key on it, players rename',
  first_join             DATETIME(3)  NOT NULL COMMENT 'UTC',
  last_seen              DATETIME(3)  NOT NULL COMMENT 'UTC',
  rules_version_accepted VARCHAR(20)       NULL COMMENT 'NULL = has not accepted. Acceptance row 17 requires the VERSION be stored, not just a boolean, so a rules change can re-gate everyone',
  rules_accepted_at      DATETIME(3)       NULL COMMENT 'UTC',
  first_ip_hash          CHAR(64)          NULL COMMENT 'SHA-256 of the IP, never the IP itself. Row 32 needs same-IP kill detection; that needs comparison, not readability. 31.13 governs retention',
  anonymised_at          DATETIME(3)       NULL COMMENT 'UTC. Set by a 31.13 deletion request; when set, current_name and first_ip_hash are scrubbed',
  created_at             DATETIME(3)  NOT NULL COMMENT 'UTC',
  updated_at             DATETIME(3)  NOT NULL COMMENT 'UTC',
  PRIMARY KEY (uuid),
  KEY idx_players_current_name (current_name) COMMENT 'for staff lookup by name; NOT a unique key, because a freed name can be taken by another account',
  KEY idx_players_last_seen (last_seen)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- access_grants - the paywall's memory. Why someone is allowed to connect
-- ---------------------------------------------------------------------------
-- Retention: permanent. A refund dispute six months later is settled from here,
-- so a revoked grant is marked revoked and never deleted.
--
-- expires_at is NULLABLE ON PURPOSE. Decision D-0002 and spec 24.1: the owner has
-- not chosen between one-time and recurring pricing. NULL means "never expires"
-- (one-time), a value means recurring. Both models are therefore already
-- supported and the pricing decision costs no schema change later.
CREATE TABLE IF NOT EXISTS access_grants (
  id                 BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid               CHAR(36)        NOT NULL COMMENT 'FK to players.uuid',
  source             VARCHAR(30)     NOT NULL COMMENT 'store, manual, founder, staff, compensation - how access was obtained. Row 12 audits the whitelist against paid transactions, so an unpaid grant must be explainable',
  transaction_ref    VARCHAR(120)         NULL COMMENT 'the store or payment provider reference. NULL only for non-purchase sources',
  amount_minor       BIGINT               NULL COMMENT 'amount actually paid, in the minor unit (paise). Integer, never a float',
  currency           CHAR(3)              NULL COMMENT 'ISO 4217, expected INR',
  granted_at         DATETIME(3)     NOT NULL COMMENT 'UTC',
  expires_at         DATETIME(3)          NULL COMMENT 'UTC. NULL = never expires; see the note above',
  revoked_at         DATETIME(3)          NULL COMMENT 'UTC. Set on refund or chargeback',
  revoked_reason     VARCHAR(200)         NULL,
  created_at         DATETIME(3)     NOT NULL COMMENT 'UTC',
  updated_at         DATETIME(3)     NOT NULL COMMENT 'UTC',
  PRIMARY KEY (id),
  UNIQUE KEY uq_access_transaction_ref (transaction_ref) COMMENT 'the same payment can never grant access twice - this is what makes the webhook safe to retry, and payment webhooks WILL be delivered more than once',
  KEY idx_access_uuid (uuid),
  KEY idx_access_active (uuid, revoked_at, expires_at) COMMENT 'the join-time question: does this player have a live grant',
  CONSTRAINT fk_access_player FOREIGN KEY (uuid) REFERENCES players (uuid) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- seasons - the monthly cycle
-- ---------------------------------------------------------------------------
-- Retention: permanent.
--
-- reset_completed exists because 31.1 and acceptance row 33 require the season
-- reset to be IDEMPOTENT and to survive interruption. A reset that crashes
-- halfway must be resumable, and that is impossible without a durable flag.
CREATE TABLE IF NOT EXISTS seasons (
  season_number     INT UNSIGNED  NOT NULL COMMENT 'monotonic from 1',
  starts_at         DATETIME(3)   NOT NULL COMMENT 'UTC',
  ends_at           DATETIME(3)   NOT NULL COMMENT 'UTC. 31.1 fixes the instant; storing it avoids recomputing it from a clock later',
  state             ENUM('pending','active','finale','resetting','archived') NOT NULL DEFAULT 'pending',
  reset_completed   TINYINT(1)    NOT NULL DEFAULT 0 COMMENT 'row 33: the reset must be idempotent, so it needs a durable did-this-finish flag',
  reset_started_at  DATETIME(3)        NULL COMMENT 'UTC',
  reset_finished_at DATETIME(3)        NULL COMMENT 'UTC',
  created_at        DATETIME(3)   NOT NULL COMMENT 'UTC',
  updated_at        DATETIME(3)   NOT NULL COMMENT 'UTC',
  PRIMARY KEY (season_number),
  KEY idx_seasons_state (state)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- champions - exactly one per season, enforced by the DATABASE
-- ---------------------------------------------------------------------------
-- Retention: permanent. This is the Hall of Fame.
--
-- ACCEPTANCE ROW 36 IS THE REASON THIS TABLE EXISTS IN PHASE 0. It requires
-- "exactly one Champion per season", with evidence "schema plus failed-insert
-- test". So the guarantee must live in the schema: PRIMARY KEY on season_number
-- means a second champion for a season is rejected by MariaDB itself, and no
-- application bug, race condition or manual console command can produce two.
-- Application-level checking would satisfy the words and not the intent.
CREATE TABLE IF NOT EXISTS champions (
  season_number  INT UNSIGNED  NOT NULL COMMENT 'PRIMARY KEY: this IS the one-champion-per-season guarantee (row 36)',
  uuid           CHAR(36)      NOT NULL COMMENT 'FK to players.uuid',
  final_rp       INT           NOT NULL COMMENT 'rating at the moment of victory',
  awarded_at     DATETIME(3)   NOT NULL COMMENT 'UTC',
  created_at     DATETIME(3)   NOT NULL COMMENT 'UTC',
  PRIMARY KEY (season_number),
  KEY idx_champions_uuid (uuid),
  CONSTRAINT fk_champion_player FOREIGN KEY (uuid) REFERENCES players (uuid) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_champion_season FOREIGN KEY (season_number) REFERENCES seasons (season_number) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
LT_SQL_EOF_V1__init_sql

# ---- stage V2__combat_stats_and_moderation.sql ----
sudo -n tee "$WORK/V2__combat_stats_and_moderation.sql" > /dev/null <<'LT_SQL_EOF_V2__combat_stats_and_moderation_sql'
-- V2__combat_stats_and_moderation.sql
--
-- Appendix D tables for the combat/rank layer (Section 9) and the moderation layer
-- (Section 14, 17). Forward-only: once applied, never edited. Corrections arrive as V3.
--
-- WHAT THIS DOES NOT DECIDE. The Elo CONSTANTS are not here and cannot be, because
-- Appendix B contradicts Section 9 in three places - questions.md Q-11 to Q-13 record
-- them: MAX_GAIN = 40 is unreachable when raw = 24 * (1 - E); the death floor is "the
-- bottom of the ladder" in 9.2 but max(tier_floor(...)) in Appendix B, which removes
-- demotion entirely; and decay is "1% per week above the tier floor" in 9.2 but
-- CR * (1 - DECAY_RATE) in Appendix B, a twentyfold difference at CR 2000.
-- Schema can be built without resolving those; the rating LOGIC cannot. Storing a
-- rating needs no opinion about how it is calculated.
--
-- Money is BIGINT, timestamps are DATETIME(3) UTC, UUIDs are CHAR(36) ascii_bin -
-- same conventions as V1, and D-0024 records why each was chosen.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- ---------------------------------------------------------------------------
-- combat_ratings - the ladder. PER SEASON, unlike stats.
-- ---------------------------------------------------------------------------
-- 9.x: rank resets each season, but the history is kept. So the primary key is
-- (uuid, season_number) rather than uuid alone - a player has one rating per season
-- and every past season's final rating stays queryable for the Hall of Fame and for
-- "seasons played, best finish" in 9.8.
--
-- Retention: permanent.
CREATE TABLE IF NOT EXISTS combat_ratings (
  uuid            CHAR(36)      NOT NULL,
  season_number   INT UNSIGNED  NOT NULL,
  current_rp      INT           NOT NULL COMMENT 'rating points. INT not DECIMAL: Appendix B works in whole points',
  peak_rp         INT           NOT NULL COMMENT 'highest reached THIS season - 9.8 shows peak, and a player who falls should not lose the record of having climbed',
  games_counted   INT UNSIGNED  NOT NULL DEFAULT 0 COMMENT 'kills that actually affected rating, after anti-farm filtering. Distinct from stats.kills, which counts everything',
  last_change_at  DATETIME(3)        NULL COMMENT 'UTC. Feeds the 9.2 inactivity decay',
  created_at      DATETIME(3)   NOT NULL COMMENT 'UTC',
  updated_at      DATETIME(3)   NOT NULL COMMENT 'UTC',
  PRIMARY KEY (uuid, season_number),
  KEY idx_cr_season_rank (season_number, current_rp DESC) COMMENT 'the leaderboard query: top N for a season',
  KEY idx_cr_decay (season_number, last_change_at) COMMENT 'finds who is due decay without scanning',
  CONSTRAINT fk_cr_player FOREIGN KEY (uuid) REFERENCES players (uuid) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_cr_season FOREIGN KEY (season_number) REFERENCES seasons (season_number) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- combat_events - every kill, and WHY it scored what it scored
-- ---------------------------------------------------------------------------
-- This table is the evidence base for four separate acceptance rows, which is why it
-- records the reasoning and not just the outcome:
--   row 30  two hours of mining moves RP by exactly zero  - provable only if every
--           RP change has a row here and mining produces none
--   row 31  diminishing returns on repeat kills           - needs the multiplier stored
--   row 32  same-IP kills award zero RP and raise an alert - needs the IP comparison
--           result stored, which is why same_ip is a column and not a log line
--   row 14a wagering detection correlates a Berry payment with a death inside 60s -
--           needs an exact timestamp on the death
--
-- Storing `rp_delta` AND `multiplier_applied` AND `suppressed_reason` means a player
-- disputing their rating can be shown precisely what happened. A single delta column
-- would make every dispute an argument.
--
-- Retention: this grows without bound, so it has a policy - 31.13 governs it. Kept at
-- full detail for the season, then archived to season_archive and pruned.
CREATE TABLE IF NOT EXISTS combat_events (
  id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  season_number       INT UNSIGNED    NOT NULL,
  killer_uuid         CHAR(36)             NULL COMMENT 'NULL when the death had no player killer - environmental, mob, or fall',
  victim_uuid         CHAR(36)        NOT NULL,
  killer_rp_before    INT                  NULL,
  victim_rp_before    INT                  NULL,
  rp_delta_killer     INT             NOT NULL DEFAULT 0 COMMENT 'what the killer actually gained, after every multiplier and suppression',
  rp_delta_victim     INT             NOT NULL DEFAULT 0 COMMENT 'normally negative',
  multiplier_applied  DECIMAL(5,4)    NOT NULL DEFAULT 1.0000 COMMENT 'the diminishing-returns factor from 9.x. DECIMAL not FLOAT - this number is shown to players and must not drift',
  suppressed_reason   VARCHAR(40)          NULL COMMENT 'NULL means it counted. Otherwise why not: same_ip, repeat_kill, staff_excluded, combat_log, self_inflicted, new_player_grace',
  same_ip             TINYINT(1)      NOT NULL DEFAULT 0 COMMENT 'row 32. Compared as hashes, never storing the address itself',
  world               VARCHAR(48)          NULL,
  x                   INT                  NULL,
  y                   INT                  NULL,
  z                   INT                  NULL,
  occurred_at         DATETIME(3)     NOT NULL COMMENT 'UTC. Millisecond precision because row 14a correlates against a 60-second window',
  PRIMARY KEY (id),
  KEY idx_ce_killer (killer_uuid, occurred_at),
  KEY idx_ce_victim (victim_uuid, occurred_at),
  KEY idx_ce_pair (killer_uuid, victim_uuid, occurred_at) COMMENT 'the repeat-kill question: how often has A killed B recently',
  KEY idx_ce_season (season_number, occurred_at),
  KEY idx_ce_suppressed (suppressed_reason) COMMENT 'for the row 32 alerting query',
  CONSTRAINT fk_ce_victim FOREIGN KEY (victim_uuid) REFERENCES players (uuid) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- stats - 9.8's list. LIFETIME, not per season
-- ---------------------------------------------------------------------------
-- "All stats persist across seasons" (9.8), so this is keyed on uuid alone.
--
-- Fixed columns for the fixed stats, and two child tables for the two that are
-- open-ended ("mob kills BY TYPE", "distance travelled BY METHOD"). The alternative -
-- one key/value table for everything - was rejected: it would make every read a pivot
-- and lose type safety on counters that are summed and compared constantly.
--
-- playtime is stored in SECONDS. 9.8's display rule - "hours until 24, then days and
-- hours" - is a formatting decision and belongs in the plugin, not the schema. Storing
-- a pre-formatted value is how you end up unable to sum it.
CREATE TABLE IF NOT EXISTS stats (
  uuid                CHAR(36)        NOT NULL,
  kills               INT UNSIGNED    NOT NULL DEFAULT 0 COMMENT 'every kill. Only kills feed rank, but not every kill feeds rank - see combat_events.suppressed_reason',
  deaths              INT UNSIGNED    NOT NULL DEFAULT 0,
  killstreak_current  INT UNSIGNED    NOT NULL DEFAULT 0,
  killstreak_best     INT UNSIGNED    NOT NULL DEFAULT 0 COMMENT '9.8: "current and best ever"',
  blocks_mined        BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '9.8 marks this informational only. Row 30 depends on it having no effect on rank',
  blocks_placed       BIGINT UNSIGNED NOT NULL DEFAULT 0,
  playtime_seconds    BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'ACTIVE playtime. 7.3 requires claim accrual to ignore AFK, so idle time must be excluded here too or the two disagree',
  seasons_played      INT UNSIGNED    NOT NULL DEFAULT 0,
  best_finish         INT UNSIGNED         NULL COMMENT 'best season placement, 1 = Champion. NULL = never finished a season',
  champion_titles     INT UNSIGNED    NOT NULL DEFAULT 0 COMMENT '9.8: "the stat everyone wants"',
  created_at          DATETIME(3)     NOT NULL COMMENT 'UTC',
  updated_at          DATETIME(3)     NOT NULL COMMENT 'UTC',
  PRIMARY KEY (uuid),
  KEY idx_stats_kills (kills DESC),
  CONSTRAINT fk_stats_player FOREIGN KEY (uuid) REFERENCES players (uuid) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stats_mob_kills (
  uuid       CHAR(36)        NOT NULL,
  mob_type   VARCHAR(64)     NOT NULL COMMENT 'the Bukkit EntityType name, stored as text so a new mob in a future version needs no migration',
  kills      BIGINT UNSIGNED NOT NULL DEFAULT 0,
  updated_at DATETIME(3)     NOT NULL COMMENT 'UTC',
  PRIMARY KEY (uuid, mob_type),
  CONSTRAINT fk_smk_player FOREIGN KEY (uuid) REFERENCES players (uuid) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stats_distance (
  uuid       CHAR(36)        NOT NULL,
  method     VARCHAR(32)     NOT NULL COMMENT 'walk, sprint, swim, boat, minecart, elytra, horse, fall - 9.8 says "by method"',
  centimetres BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Minecraft measures movement in centimetres internally; storing its own unit avoids rounding on every update',
  updated_at DATETIME(3)     NOT NULL COMMENT 'UTC',
  PRIMARY KEY (uuid, method),
  CONSTRAINT fk_sd_player FOREIGN KEY (uuid) REFERENCES players (uuid) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- punishments - the published ladder (14.4), applied
-- ---------------------------------------------------------------------------
-- Retention: permanent. An expired ban is still evidence, and 17.4 requires that staff
-- cannot delete the record of what staff did. Expiry is a timestamp, never a deletion.
CREATE TABLE IF NOT EXISTS punishments (
  id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  target_uuid    CHAR(36)        NOT NULL,
  type           ENUM('warn','mute','kick','tempban','ban','voice_mute') NOT NULL,
  reason         VARCHAR(500)    NOT NULL,
  evidence_ref   VARCHAR(300)         NULL COMMENT 'link or id for the evidence. 14.x requires punishments be evidenced, not asserted',
  rule_broken    VARCHAR(60)          NULL COMMENT 'which published rule, so the ladder in 14.4 can be audited for consistency',
  issued_by      CHAR(36)             NULL COMMENT 'NULL means Console - an automated action, which must be distinguishable from a human one',
  issued_at      DATETIME(3)     NOT NULL COMMENT 'UTC',
  expires_at     DATETIME(3)          NULL COMMENT 'UTC. NULL = permanent',
  revoked_at     DATETIME(3)          NULL COMMENT 'UTC. Set when overturned on appeal',
  revoked_by     CHAR(36)             NULL,
  revoked_reason VARCHAR(500)         NULL,
  reviewed_by    CHAR(36)             NULL COMMENT '17.4 wants a two-person rule for permanent bans where possible: one issues, one reviews',
  PRIMARY KEY (id),
  KEY idx_pun_target (target_uuid, issued_at),
  KEY idx_pun_active (target_uuid, type, revoked_at, expires_at) COMMENT 'the join-time question: is this player currently banned or muted',
  KEY idx_pun_staff (issued_by, issued_at) COMMENT 'for reviewing a staff member''s pattern of punishments',
  CONSTRAINT fk_pun_target FOREIGN KEY (target_uuid) REFERENCES players (uuid) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- reports - player reports and their handling
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reports (
  id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  reporter_uuid CHAR(36)        NOT NULL,
  target_uuid   CHAR(36)        NOT NULL,
  reason        VARCHAR(500)    NOT NULL,
  evidence_ref  VARCHAR(300)         NULL,
  state         ENUM('open','claimed','resolved','rejected','duplicate') NOT NULL DEFAULT 'open',
  handled_by    CHAR(36)             NULL,
  handled_at    DATETIME(3)          NULL COMMENT 'UTC',
  resolution    VARCHAR(500)         NULL,
  created_at    DATETIME(3)     NOT NULL COMMENT 'UTC',
  PRIMARY KEY (id),
  KEY idx_rep_state (state, created_at) COMMENT 'the staff queue, oldest first',
  KEY idx_rep_target (target_uuid, created_at) COMMENT 'is this player being repeatedly reported',
  KEY idx_rep_reporter (reporter_uuid, created_at) COMMENT 'and is this reporter abusing the system',
  CONSTRAINT fk_rep_reporter FOREIGN KEY (reporter_uuid) REFERENCES players (uuid) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_rep_target   FOREIGN KEY (target_uuid)   REFERENCES players (uuid) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- staff_audit - APPEND ONLY, and enforced as such
-- ---------------------------------------------------------------------------
-- Appendix D marks this append-only and 17.3 puts audit-log access on the
-- never-grant-to-Admin list: "Staff must not be able to read or edit the record of what
-- staff did."
--
-- The append-only property is enforced by TRIGGERS, not by convention. A comment saying
-- "do not update this" is a request; a trigger that raises SQLSTATE 45000 on UPDATE or
-- DELETE is a guarantee - the same reasoning as the champions PRIMARY KEY in V1 and the
-- destructive-command guard. Note the app user cannot DROP the triggers either: the
-- migration runner connects as `laughtail`, which has rights inside this schema, so the
-- protection is against accident and against a compromised plugin, not against someone
-- with root. That limit is real and is stated rather than glossed.
CREATE TABLE IF NOT EXISTS staff_audit (
  id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  staff_uuid   CHAR(36)             NULL COMMENT 'NULL = Console. 17.2: automation only, no human uses console as their identity',
  staff_name   VARCHAR(32)          NULL COMMENT 'denormalised on purpose: the audit must still read correctly after a rename or an account deletion',
  action       VARCHAR(64)     NOT NULL COMMENT 'the command or operation performed',
  target_uuid  CHAR(36)             NULL,
  target_name  VARCHAR(32)          NULL,
  parameters   TEXT                 NULL COMMENT 'full arguments. Appendix D asks for who, what, when and to whom',
  world        VARCHAR(48)          NULL,
  occurred_at  DATETIME(3)     NOT NULL COMMENT 'UTC',
  PRIMARY KEY (id),
  KEY idx_audit_staff (staff_uuid, occurred_at),
  KEY idx_audit_target (target_uuid, occurred_at),
  KEY idx_audit_action (action, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- The append-only enforcement. Written as SINGLE-STATEMENT triggers on purpose: a
-- BEGIN...END body would need a DELIMITER directive, which is a client-side feature and
-- would make this file dependent on how it is piped in. One statement each, no
-- delimiter games, works identically however it is applied.
CREATE TRIGGER IF NOT EXISTS staff_audit_no_update
  BEFORE UPDATE ON staff_audit FOR EACH ROW
  SIGNAL SQLSTATE '45000'
  SET MESSAGE_TEXT = 'staff_audit is append-only (Appendix D, spec 17.3): rows cannot be modified';

CREATE TRIGGER IF NOT EXISTS staff_audit_no_delete
  BEFORE DELETE ON staff_audit FOR EACH ROW
  SIGNAL SQLSTATE '45000'
  SET MESSAGE_TEXT = 'staff_audit is append-only (Appendix D, spec 17.3): rows cannot be deleted';

-- ---------------------------------------------------------------------------
-- preferences - the Section 16 settings menu
-- ---------------------------------------------------------------------------
-- Key/value here, unlike stats, and for the opposite reason: these are read once per
-- session and never aggregated, the set will grow as the menu grows, and a new toggle
-- should not need a migration.
CREATE TABLE IF NOT EXISTS preferences (
  uuid       CHAR(36)     NOT NULL,
  pref_key   VARCHAR(48)  NOT NULL,
  pref_value VARCHAR(200) NOT NULL,
  updated_at DATETIME(3)  NOT NULL COMMENT 'UTC',
  PRIMARY KEY (uuid, pref_key),
  CONSTRAINT fk_pref_player FOREIGN KEY (uuid) REFERENCES players (uuid) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
LT_SQL_EOF_V2__combat_stats_and_moderation_sql

# ---- stage V3__economy.sql ----
sudo -n tee "$WORK/V3__economy.sql" > /dev/null <<'LT_SQL_EOF_V3__economy_sql'
-- V3__economy.sql
--
-- Berries: the single currency (Law: one currency, no dual-currency hyperinflation), its
-- ledger, and the shop's price state. Appendix D's economy tables.
--
-- NOW BUILDABLE because D-0031 fixed the numbers Q-10 was blocking on:
--   target_berries_per_hour 1200, minimum spread 12%, elasticity 0.15 per 1000 units with a
--   +/-40% band, recovery 5% of the gap per hour, daily sell cap 3600 per category,
--   transfer tax 5% above 5000.
--
-- THE LEDGER IS THE POINT. `balances` is a cache of `transactions`, not the other way round.
-- Every movement writes a transaction row, and a balance is only ever changed in the same
-- transaction that records why. That is what makes the Phase 3 arbitrage audit possible at
-- all: an audit that cannot see every movement cannot find a money printer.
--
-- MONEY IS BIGINT, in whole Berries. Not DECIMAL, not double. A float balance cannot be
-- summed reliably across a million rows, and the arbitrage audit sums.

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- ---------------------------------------------------------------------------
-- balances - current holdings. A CACHE of the ledger.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS balances (
  uuid          CHAR(36)     NOT NULL,
  berries       BIGINT       NOT NULL DEFAULT 0 COMMENT 'whole Berries. Signed BIGINT deliberately: a negative balance should be IMPOSSIBLE, and storing it unsigned would make an underflow wrap to a vast positive number instead of failing. A CHECK enforces it below',
  lifetime_in   BIGINT       NOT NULL DEFAULT 0 COMMENT 'total ever earned - for the 31.10 growth alert, which needs a rate and not just a level',
  lifetime_out  BIGINT       NOT NULL DEFAULT 0,
  last_modified DATETIME(3)  NOT NULL COMMENT 'UTC',
  created_at    DATETIME(3)  NOT NULL COMMENT 'UTC',
  PRIMARY KEY (uuid),
  KEY idx_bal_amount (berries DESC) COMMENT 'the rich list, and the median for the P7 alert',
  CONSTRAINT chk_bal_nonneg CHECK (berries >= 0),
  CONSTRAINT fk_bal_player FOREIGN KEY (uuid) REFERENCES players (uuid)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- transactions - every Berry movement, permanently
-- ---------------------------------------------------------------------------
-- Appendix D: "Every Berry movement, with type, counterparty, amount, and reason."
--
-- Retention: permanent, and deliberately so. This is the evidence base for the arbitrage
-- audit, for row 14a's wagering detector (a payment correlated with a death inside 60
-- seconds, hence DATETIME(3)), and for any dispute about where money went. 31.13 governs
-- personal data, not the ledger - anonymising a player scrubs their name, not their trades.
--
-- balance_after is stored ON EACH ROW. That is denormalised on purpose: it makes the ledger
-- self-checking. If row N's balance_after plus row N+1's delta does not equal row N+1's
-- balance_after, the ledger has been corrupted and it can be found by scanning rather than
-- by reconstructing from zero.
CREATE TABLE IF NOT EXISTS transactions (
  id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  uuid           CHAR(36)        NOT NULL COMMENT 'whose balance moved',
  delta          BIGINT          NOT NULL COMMENT 'signed. Positive is income, negative is spend',
  balance_after  BIGINT          NOT NULL COMMENT 'denormalised so the ledger is self-checking - see the note above',
  type           VARCHAR(32)     NOT NULL COMMENT 'shop_buy, shop_sell, transfer_in, transfer_out, transfer_tax, auction_sale, auction_fee, admin_grant, admin_take, sink_fee, bounty, reward',
  counterparty   CHAR(36)             NULL COMMENT 'the other player, when there is one. NULL for shop and system movements',
  item            VARCHAR(64)         NULL COMMENT 'the item involved, for shop and auction rows',
  quantity        INT                 NULL,
  reason         VARCHAR(200)         NULL COMMENT 'human-readable, for disputes',
  occurred_at    DATETIME(3)     NOT NULL COMMENT 'UTC, millisecond precision for row 14a',
  PRIMARY KEY (id),
  KEY idx_tx_player (uuid, occurred_at),
  KEY idx_tx_type (type, occurred_at),
  KEY idx_tx_counterparty (counterparty, occurred_at) COMMENT 'reciprocal-transfer detection',
  KEY idx_tx_item (item, occurred_at) COMMENT 'the arbitrage audit walks by item',
  CONSTRAINT fk_tx_player FOREIGN KEY (uuid) REFERENCES players (uuid)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- shop_prices - the dynamic price band of 8.x
-- ---------------------------------------------------------------------------
-- base_price is derived from Appendix B's base-value formula against
-- target_berries_per_hour = 1200 (P2). current_price moves with trade under P4's elasticity
-- and drifts back under P5's recovery.
--
-- The band is enforced in the SCHEMA as well as in code, because "prices stay within a
-- bounded band" is the property that stops a money printer, and a bounded band enforced only
-- by application logic is one bug away from unbounded.
CREATE TABLE IF NOT EXISTS shop_prices (
  item           VARCHAR(64)  NOT NULL COMMENT 'Bukkit Material name',
  category       VARCHAR(32)  NOT NULL COMMENT 'for the P6 daily sell cap, which is per category so rotating between similar items does not dodge it',
  base_price     BIGINT       NOT NULL COMMENT 'derived from P2. Never changes at runtime',
  current_price  BIGINT       NOT NULL COMMENT 'moves with trade, bounded to +/-40% of base (P4)',
  sell_price     BIGINT       NOT NULL COMMENT 'current_price minus the 12% minimum spread (P3)',
  units_traded   BIGINT       NOT NULL DEFAULT 0 COMMENT 'drives elasticity',
  last_trade_at  DATETIME(3)       NULL COMMENT 'UTC. Drives the P5 recovery toward base',
  updated_at     DATETIME(3)  NOT NULL COMMENT 'UTC',
  PRIMARY KEY (item),
  KEY idx_price_category (category),
  CONSTRAINT chk_price_band CHECK (current_price >= base_price * 0.6
                               AND current_price <= base_price * 1.4),
  CONSTRAINT chk_spread CHECK (sell_price < current_price)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- daily_sell_totals - the P6 cap, per player per category per UTC day
-- ---------------------------------------------------------------------------
-- A separate table rather than a rolling query over `transactions`, because the cap is
-- checked on every sale and scanning the ledger for each one would put a growing query in a
-- hot path. This is a counter that resets by date, which is cheap to read and cheap to reset
-- by simply having a different key tomorrow.
CREATE TABLE IF NOT EXISTS daily_sell_totals (
  uuid       CHAR(36)     NOT NULL,
  sell_date  DATE         NOT NULL COMMENT 'UTC date, so the cap resets at the same instant for everyone regardless of timezone',
  category   VARCHAR(32)  NOT NULL,
  berries    BIGINT       NOT NULL DEFAULT 0,
  updated_at DATETIME(3)  NOT NULL COMMENT 'UTC',
  PRIMARY KEY (uuid, sell_date, category),
  CONSTRAINT fk_dst_player FOREIGN KEY (uuid) REFERENCES players (uuid)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- shop_tier_state - which shop tier a player has unlocked (Section 10)
-- ---------------------------------------------------------------------------
-- Tier derives from rank, so this is a cache with a peak, exactly like combat_ratings. Kept
-- per season because rank resets, and `peak_tier` is kept because 10.x gates purchases on
-- what a player has REACHED rather than on where they currently sit - otherwise a bad week
-- would revoke access to items they already earned.
CREATE TABLE IF NOT EXISTS shop_tier_state (
  uuid          CHAR(36)      NOT NULL,
  season_number INT UNSIGNED  NOT NULL,
  current_tier  TINYINT       NOT NULL DEFAULT 1,
  peak_tier     TINYINT       NOT NULL DEFAULT 1,
  updated_at    DATETIME(3)   NOT NULL COMMENT 'UTC',
  PRIMARY KEY (uuid, season_number),
  CONSTRAINT chk_tier_range CHECK (current_tier BETWEEN 1 AND 8 AND peak_tier BETWEEN 1 AND 8),
  CONSTRAINT fk_sts_player FOREIGN KEY (uuid) REFERENCES players (uuid)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
LT_SQL_EOF_V3__economy_sql

# ---- stage V4__homes_and_teleports.sql ----
sudo -n tee "$WORK/V4__homes_and_teleports.sql" > /dev/null <<'LT_SQL_EOF_V4__homes_and_teleports_sql'
-- V4__homes_and_teleports.sql
--
-- Section 15: homes up to 20, rename, home-to-home, with slots bought using Berries. Plus the
-- teleport guards 15.x requires, and the friends list from D-0035's new-feature set.
--
-- WHY HOME SLOTS ARE A COLUMN AND NOT A COUNT OF ROWS. The obvious design stores homes and
-- counts them against a limit derived from rank. That breaks the moment a player is demoted:
-- their 8th home would become invalid and either vanish or block a save. Storing the purchased
-- allowance separately means a slot bought with Berries is OWNED - demotion can take a tier,
-- it cannot take something that was paid for. Same principle as cosmetics_owned in Appendix D,
-- which is explicitly "never deleted by a reset".

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- ---------------------------------------------------------------------------
-- homes
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS homes (
  uuid        CHAR(36)     NOT NULL,
  name        VARCHAR(24)  NOT NULL COMMENT 'lowercased on write so "Base" and "base" are the same home rather than two',
  world       VARCHAR(48)  NOT NULL,
  x           DOUBLE       NOT NULL,
  y           DOUBLE       NOT NULL,
  z           DOUBLE       NOT NULL,
  yaw         FLOAT        NOT NULL DEFAULT 0 COMMENT 'stored so a player faces the way they were looking - a home that spins you round feels broken',
  pitch       FLOAT        NOT NULL DEFAULT 0,
  created_at  DATETIME(3)  NOT NULL COMMENT 'UTC',
  updated_at  DATETIME(3)  NOT NULL COMMENT 'UTC',
  PRIMARY KEY (uuid, name),
  KEY idx_homes_world (world) COMMENT 'so a world deletion can find the homes it would orphan - the resource world resets monthly',
  CONSTRAINT fk_homes_player FOREIGN KEY (uuid) REFERENCES players (uuid)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- home_slots - the purchased allowance, owned permanently
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS home_slots (
  uuid            CHAR(36)     NOT NULL,
  purchased_slots INT          NOT NULL DEFAULT 0 COMMENT 'bought with Berries. Never revoked, never reset - a slot paid for is owned (see the header note)',
  total_spent     BIGINT       NOT NULL DEFAULT 0 COMMENT 'for the ledger cross-check and for a refund conversation',
  updated_at      DATETIME(3)  NOT NULL COMMENT 'UTC',
  PRIMARY KEY (uuid),
  -- 15.x caps homes at 20; 2 are free, so at most 18 can ever be bought.
  -- NOTE: MariaDB does not accept COMMENT on a CHECK constraint - it parses as a syntax
  -- error, which is how this migration failed on its first attempt. The runner refused to
  -- record it, which is exactly what forward-only migrations must do with a failure.
  CONSTRAINT chk_slots_range CHECK (purchased_slots BETWEEN 0 AND 18),
  CONSTRAINT fk_slots_player FOREIGN KEY (uuid) REFERENCES players (uuid)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- friends - mutual, and stored once rather than twice
-- ---------------------------------------------------------------------------
-- The pair is stored with the LOWER uuid first and a CHECK enforcing it. Storing both
-- directions is the usual approach and it is worse: two rows can disagree, and "are we
-- friends" becomes a question with two possible answers. One canonical row cannot disagree
-- with itself.
CREATE TABLE IF NOT EXISTS friends (
  uuid_low    CHAR(36)     NOT NULL,
  uuid_high   CHAR(36)     NOT NULL,
  requested_by CHAR(36)    NOT NULL COMMENT 'who asked - needed to show a pending request to the right person',
  state       ENUM('pending','accepted') NOT NULL DEFAULT 'pending',
  created_at  DATETIME(3)  NOT NULL COMMENT 'UTC',
  updated_at  DATETIME(3)  NOT NULL COMMENT 'UTC',
  PRIMARY KEY (uuid_low, uuid_high),
  KEY idx_friends_state (state),
  -- The canonical ordering (uuid_low < uuid_high) is enforced in APPLICATION CODE, not here.
  -- MariaDB rejects a CHECK that compares two columns in this position with
  -- ERROR 1901: Function or expression 'uuid_low' cannot be used in the CHECK clause.
  -- That is a real limitation rather than a preference, so the invariant lives in one place
  -- instead of two - and it is stated here so the next person does not assume the database
  -- is guarding it. Everything that writes this table must order the pair first.
  CONSTRAINT fk_friend_low  FOREIGN KEY (uuid_low)  REFERENCES players (uuid)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_friend_high FOREIGN KEY (uuid_high) REFERENCES players (uuid)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
LT_SQL_EOF_V4__homes_and_teleports_sql

# ---- stage V5__market.sql ----
sudo -n tee "$WORK/V5__market.sql" > /dev/null <<'LT_SQL_EOF_V5__market_sql'
-- V5 - the auction house and the order book (bazaar).
--
-- Two different markets, deliberately, because they solve different problems:
--
--   AUCTIONS are for ONE specific item at a fixed price. The item may be enchanted, named, damaged -
--   anything - so it is stored as a serialised stack. You browse, you buy, you get that exact item.
--
--   ORDERS are for FUNGIBLE resources: 500 iron, any iron. Buy orders and sell orders sit in a book
--   and are matched automatically. Nobody has to be online for a trade to happen, which is the whole
--   point of a bazaar and the reason it is not just an auction with extra steps.
--
-- WHY ESCROW IS IN THE DATABASE AND NOT IN MEMORY. Acceptance row 28 requires that killing the
-- server mid-match "creates and destroys nothing". Anything held in a Java map is gone on restart,
-- and the player is either down an item or up a duplicate. So a listed item leaves the player's
-- inventory and becomes a row; Berries committed to a buy order leave the balance and become a row.
-- The database is the only thing that survives a kill -9, so the database is where value lives.
--
-- WHY ORDERS DO NOT STORE A SERIALISED STACK. An order is for a material and a quantity, nothing
-- more. Allowing NBT in the order book would mean a buy order for "iron ingot" could be filled with
-- a renamed iron ingot, or a differently enchanted one, and every fill would need a comparison
-- nobody can reason about. Fungible means fungible. Anything with NBT goes to the auction house.

-- COLLATE IS EXPLICIT. Without it these tables take the server default (utf8mb4_general_ci) while
-- players.uuid is utf8mb4_unicode_ci, and a foreign key between two different collations fails with
-- the famously unhelpful "errno: 150 Foreign key constraint is incorrectly formed". Every table in
-- this schema states its collation for that reason.
SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- ---------------------------------------------------------------------------
-- auctions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS auctions (
  id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  seller        CHAR(36)        NOT NULL,
  item_blob     BLOB            NOT NULL COMMENT 'Bukkit serializeAsBytes. The item itself lives here, not in anyone inventory, so a restart cannot lose it',
  item_name     VARCHAR(64)     NOT NULL COMMENT 'Material name, denormalised for searching and for the GUI - reading every blob to render a page would be absurd',
  display_name  VARCHAR(128)        NULL COMMENT 'custom name if the item had one, so a listing shows what a player would recognise',
  quantity      INT UNSIGNED    NOT NULL,
  price         BIGINT UNSIGNED NOT NULL COMMENT 'total price for the whole stack, not per unit - a fixed-price listing is one decision, not arithmetic',
  state         ENUM('active','sold','expired','cancelled') NOT NULL DEFAULT 'active',
  buyer         CHAR(36)            NULL,
  created_at    DATETIME(3)     NOT NULL COMMENT 'UTC',
  expires_at    DATETIME(3)     NOT NULL COMMENT 'UTC',
  resolved_at   DATETIME(3)         NULL COMMENT 'UTC. When it sold, expired or was cancelled',
  claimed       TINYINT(1)      NOT NULL DEFAULT 0 COMMENT 'whether the seller has collected the proceeds or the unsold item back',
  PRIMARY KEY (id),
  KEY idx_auction_active (state, expires_at),
  KEY idx_auction_seller (seller, state),
  KEY idx_auction_item (item_name, state),
  CONSTRAINT fk_auction_seller FOREIGN KEY (seller) REFERENCES players (uuid),
  CONSTRAINT fk_auction_buyer  FOREIGN KEY (buyer)  REFERENCES players (uuid),
  CONSTRAINT chk_auction_price CHECK (price > 0),
  CONSTRAINT chk_auction_qty   CHECK (quantity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- orders - the bazaar
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
  id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  player         CHAR(36)        NOT NULL,
  side           ENUM('buy','sell') NOT NULL,
  material       VARCHAR(64)     NOT NULL COMMENT 'Bukkit Material name. No NBT: fungible means fungible',
  unit_price     BIGINT UNSIGNED NOT NULL,
  quantity       INT UNSIGNED    NOT NULL COMMENT 'the original size, kept so a partly filled order can still be explained',
  remaining      INT UNSIGNED    NOT NULL,
  escrow_berries BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'for buy orders: Berries already taken from the balance and held here',
  escrow_items   INT UNSIGNED    NOT NULL DEFAULT 0 COMMENT 'for sell orders: items already taken from the inventory and held here',
  payout_berries BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'proceeds waiting to be collected',
  payout_items   INT UNSIGNED    NOT NULL DEFAULT 0 COMMENT 'bought items waiting to be collected',
  state          ENUM('open','filled','cancelled') NOT NULL DEFAULT 'open',
  created_at     DATETIME(3)     NOT NULL COMMENT 'UTC. Also the tie-break for matching - time priority',
  updated_at     DATETIME(3)     NOT NULL COMMENT 'UTC',
  PRIMARY KEY (id),
  -- The matching engine scans this index: one side, one material, ordered by price then age.
  KEY idx_book (material, side, state, unit_price, created_at),
  KEY idx_order_player (player, state),
  CONSTRAINT fk_order_player FOREIGN KEY (player) REFERENCES players (uuid),
  CONSTRAINT chk_order_price CHECK (unit_price > 0),
  CONSTRAINT chk_order_qty   CHECK (quantity > 0),
  -- remaining can reach zero but must never go below it, and never exceed what was ordered.
  CONSTRAINT chk_order_remaining CHECK (remaining <= quantity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- order_fills - the audit trail for every match
-- ---------------------------------------------------------------------------
-- Every match writes a row here BEFORE the orders are updated, inside the same transaction. If a
-- fill exists, the trade happened; if it does not, it did not. That is what makes row 28 provable
-- rather than asserted - after a kill -9 the question "did this trade happen?" has exactly one
-- answer, and it is not "compare two inventories and guess".
CREATE TABLE IF NOT EXISTS order_fills (
  id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  buy_order_id  BIGINT UNSIGNED NOT NULL,
  sell_order_id BIGINT UNSIGNED NOT NULL,
  material      VARCHAR(64)     NOT NULL,
  quantity      INT UNSIGNED    NOT NULL,
  unit_price    BIGINT UNSIGNED NOT NULL COMMENT 'the price actually paid - the resting order sets it, see the note in Market.java',
  buyer         CHAR(36)        NOT NULL,
  seller        CHAR(36)        NOT NULL,
  occurred_at   DATETIME(3)     NOT NULL COMMENT 'UTC, millisecond precision',
  PRIMARY KEY (id),
  KEY idx_fill_buy (buy_order_id),
  KEY idx_fill_sell (sell_order_id),
  KEY idx_fill_time (occurred_at),
  CONSTRAINT fk_fill_buy  FOREIGN KEY (buy_order_id)  REFERENCES orders (id),
  CONSTRAINT fk_fill_sell FOREIGN KEY (sell_order_id) REFERENCES orders (id),
  CONSTRAINT chk_fill_qty CHECK (quantity > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
LT_SQL_EOF_V5__market_sql

echo "=== bootstrap: the bookkeeping table must exist before anything is recorded ==="
# Chicken and egg: schema_migrations is created BY V1, but V1 must be recorded IN
# it. So the table is created idempotently here first. V1 also declares it with
# CREATE TABLE IF NOT EXISTS, so applying V1 on a fresh database still works and
# the definition stays in version control where it belongs.
q "CREATE TABLE IF NOT EXISTS schema_migrations (version VARCHAR(20) NOT NULL, description VARCHAR(200) NOT NULL, checksum CHAR(64) NOT NULL, applied_at DATETIME(3) NOT NULL, applied_by VARCHAR(100) NOT NULL, duration_ms INT UNSIGNED NOT NULL, PRIMARY KEY (version)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;"

echo "=== checking already-applied migrations for tampering ==="
DRIFT=0
PENDING=""

# ---- V1__init.sql ----
SUM=$(sudo -n sha256sum "$WORK/V1__init.sql" | cut -d" " -f1)
REC=$(q "SELECT checksum FROM schema_migrations WHERE version='V1';" | tr -dc '0-9a-f')
if [ -z "$REC" ]; then
  echo "  V1__init.sql PENDING"
  PENDING="$PENDING V1__init.sql"
elif [ "$REC" = "$SUM" ]; then
  echo "  V1__init.sql already applied, checksum matches"
else
  echo "  V1__init.sql ALREADY APPLIED BUT CHECKSUM DIFFERS"
  echo "    recorded: $REC"
  echo "    now:      $SUM"
  DRIFT=$((DRIFT + 1))
fi

# ---- V2__combat_stats_and_moderation.sql ----
SUM=$(sudo -n sha256sum "$WORK/V2__combat_stats_and_moderation.sql" | cut -d" " -f1)
REC=$(q "SELECT checksum FROM schema_migrations WHERE version='V2';" | tr -dc '0-9a-f')
if [ -z "$REC" ]; then
  echo "  V2__combat_stats_and_moderation.sql PENDING"
  PENDING="$PENDING V2__combat_stats_and_moderation.sql"
elif [ "$REC" = "$SUM" ]; then
  echo "  V2__combat_stats_and_moderation.sql already applied, checksum matches"
else
  echo "  V2__combat_stats_and_moderation.sql ALREADY APPLIED BUT CHECKSUM DIFFERS"
  echo "    recorded: $REC"
  echo "    now:      $SUM"
  DRIFT=$((DRIFT + 1))
fi

# ---- V3__economy.sql ----
SUM=$(sudo -n sha256sum "$WORK/V3__economy.sql" | cut -d" " -f1)
REC=$(q "SELECT checksum FROM schema_migrations WHERE version='V3';" | tr -dc '0-9a-f')
if [ -z "$REC" ]; then
  echo "  V3__economy.sql PENDING"
  PENDING="$PENDING V3__economy.sql"
elif [ "$REC" = "$SUM" ]; then
  echo "  V3__economy.sql already applied, checksum matches"
else
  echo "  V3__economy.sql ALREADY APPLIED BUT CHECKSUM DIFFERS"
  echo "    recorded: $REC"
  echo "    now:      $SUM"
  DRIFT=$((DRIFT + 1))
fi

# ---- V4__homes_and_teleports.sql ----
SUM=$(sudo -n sha256sum "$WORK/V4__homes_and_teleports.sql" | cut -d" " -f1)
REC=$(q "SELECT checksum FROM schema_migrations WHERE version='V4';" | tr -dc '0-9a-f')
if [ -z "$REC" ]; then
  echo "  V4__homes_and_teleports.sql PENDING"
  PENDING="$PENDING V4__homes_and_teleports.sql"
elif [ "$REC" = "$SUM" ]; then
  echo "  V4__homes_and_teleports.sql already applied, checksum matches"
else
  echo "  V4__homes_and_teleports.sql ALREADY APPLIED BUT CHECKSUM DIFFERS"
  echo "    recorded: $REC"
  echo "    now:      $SUM"
  DRIFT=$((DRIFT + 1))
fi

# ---- V5__market.sql ----
SUM=$(sudo -n sha256sum "$WORK/V5__market.sql" | cut -d" " -f1)
REC=$(q "SELECT checksum FROM schema_migrations WHERE version='V5';" | tr -dc '0-9a-f')
if [ -z "$REC" ]; then
  echo "  V5__market.sql PENDING"
  PENDING="$PENDING V5__market.sql"
elif [ "$REC" = "$SUM" ]; then
  echo "  V5__market.sql already applied, checksum matches"
else
  echo "  V5__market.sql ALREADY APPLIED BUT CHECKSUM DIFFERS"
  echo "    recorded: $REC"
  echo "    now:      $SUM"
  DRIFT=$((DRIFT + 1))
fi

if [ "$DRIFT" -ne 0 ]; then
  echo "ABORT: $DRIFT applied migration(s) have been edited. Applying nothing."
  echo "Migrations are forward-only. Add a new V<n> instead of changing an old one."
  exit 3
fi

if [ -z "$PENDING" ]; then
  echo "=== nothing to apply. Schema is up to date. ==="
else
  echo "=== applying:$PENDING ==="
fi

case "$PENDING" in *V1__init.sql*)
  echo "--- applying V1__init.sql ---"
  START=$(date +%s%3N)
  if qfile "$WORK/V1__init.sql"; then
    END=$(date +%s%3N)
    SUM=$(sudo -n sha256sum "$WORK/V1__init.sql" | cut -d" " -f1)
    q "INSERT INTO schema_migrations (version, description, checksum, applied_at, applied_by, duration_ms) VALUES ('V1', 'init', '$SUM', UTC_TIMESTAMP(3), 'db-migrate.sh', $((END - START)));"
    echo "  applied V1__init.sql in $((END - START)) ms"
  else
    echo "  FAILED: V1__init.sql did not apply. Not recording it."
    exit 4
  fi
  ;;
esac

case "$PENDING" in *V2__combat_stats_and_moderation.sql*)
  echo "--- applying V2__combat_stats_and_moderation.sql ---"
  START=$(date +%s%3N)
  if qfile "$WORK/V2__combat_stats_and_moderation.sql"; then
    END=$(date +%s%3N)
    SUM=$(sudo -n sha256sum "$WORK/V2__combat_stats_and_moderation.sql" | cut -d" " -f1)
    q "INSERT INTO schema_migrations (version, description, checksum, applied_at, applied_by, duration_ms) VALUES ('V2', 'combat stats and moderation', '$SUM', UTC_TIMESTAMP(3), 'db-migrate.sh', $((END - START)));"
    echo "  applied V2__combat_stats_and_moderation.sql in $((END - START)) ms"
  else
    echo "  FAILED: V2__combat_stats_and_moderation.sql did not apply. Not recording it."
    exit 4
  fi
  ;;
esac

case "$PENDING" in *V3__economy.sql*)
  echo "--- applying V3__economy.sql ---"
  START=$(date +%s%3N)
  if qfile "$WORK/V3__economy.sql"; then
    END=$(date +%s%3N)
    SUM=$(sudo -n sha256sum "$WORK/V3__economy.sql" | cut -d" " -f1)
    q "INSERT INTO schema_migrations (version, description, checksum, applied_at, applied_by, duration_ms) VALUES ('V3', 'economy', '$SUM', UTC_TIMESTAMP(3), 'db-migrate.sh', $((END - START)));"
    echo "  applied V3__economy.sql in $((END - START)) ms"
  else
    echo "  FAILED: V3__economy.sql did not apply. Not recording it."
    exit 4
  fi
  ;;
esac

case "$PENDING" in *V4__homes_and_teleports.sql*)
  echo "--- applying V4__homes_and_teleports.sql ---"
  START=$(date +%s%3N)
  if qfile "$WORK/V4__homes_and_teleports.sql"; then
    END=$(date +%s%3N)
    SUM=$(sudo -n sha256sum "$WORK/V4__homes_and_teleports.sql" | cut -d" " -f1)
    q "INSERT INTO schema_migrations (version, description, checksum, applied_at, applied_by, duration_ms) VALUES ('V4', 'homes and teleports', '$SUM', UTC_TIMESTAMP(3), 'db-migrate.sh', $((END - START)));"
    echo "  applied V4__homes_and_teleports.sql in $((END - START)) ms"
  else
    echo "  FAILED: V4__homes_and_teleports.sql did not apply. Not recording it."
    exit 4
  fi
  ;;
esac

case "$PENDING" in *V5__market.sql*)
  echo "--- applying V5__market.sql ---"
  START=$(date +%s%3N)
  if qfile "$WORK/V5__market.sql"; then
    END=$(date +%s%3N)
    SUM=$(sudo -n sha256sum "$WORK/V5__market.sql" | cut -d" " -f1)
    q "INSERT INTO schema_migrations (version, description, checksum, applied_at, applied_by, duration_ms) VALUES ('V5', 'market', '$SUM', UTC_TIMESTAMP(3), 'db-migrate.sh', $((END - START)));"
    echo "  applied V5__market.sql in $((END - START)) ms"
  else
    echo "  FAILED: V5__market.sql did not apply. Not recording it."
    exit 4
  fi
  ;;
esac

echo "=== resulting schema ==="
q "SELECT TABLE_NAME, ENGINE, TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA='laughtail' ORDER BY TABLE_NAME;"

echo "=== migration history ==="
q "SELECT version, description, applied_at, duration_ms FROM schema_migrations ORDER BY version;"

echo "=== ACCEPTANCE ROW 36: the one-champion-per-season guarantee ==="
# Row 36 demands evidence of "schema plus failed-insert test". A passing test
# here means the DATABASE refuses a second champion, so no application bug, race
# or manual console command can produce two. Application-level checking would
# satisfy the wording and miss the point.
q "INSERT IGNORE INTO players (uuid, current_name, first_join, last_seen, created_at, updated_at) VALUES ('00000000-0000-4000-8000-000000000001', 'RowThirtySix', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));"
q "INSERT IGNORE INTO seasons (season_number, starts_at, ends_at, state, created_at, updated_at) VALUES (99999, UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), 'archived', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));"
q "INSERT IGNORE INTO champions (season_number, uuid, final_rp, awarded_at, created_at) VALUES (99999, '00000000-0000-4000-8000-000000000001', 2000, UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));"
echo "first champion for test season 99999:"
q "SELECT COUNT(*) AS champions_for_season FROM champions WHERE season_number=99999;"

echo "now attempting a SECOND champion for the same season - this MUST fail:"
SECOND=$(q "INSERT INTO champions (season_number, uuid, final_rp, awarded_at, created_at) VALUES (99999, '00000000-0000-4000-8000-000000000001', 9999, UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));" || true)
echo "  database said: $SECOND"
if echo "$SECOND" | grep -qi 'duplicate entry'; then
  echo "  ROW 36 PASS: the database refused the second champion."
else
  echo "  ROW 36 FAIL: the second insert was NOT refused. The constraint is not doing its job."
fi
q "SELECT COUNT(*) AS still_only_one FROM champions WHERE season_number=99999;"

echo "=== cleaning up the test rows ==="
q "DELETE FROM champions WHERE season_number=99999;"
q "DELETE FROM seasons WHERE season_number=99999;"
q "DELETE FROM players WHERE uuid='00000000-0000-4000-8000-000000000001';"
q "SELECT (SELECT COUNT(*) FROM champions) AS champions, (SELECT COUNT(*) FROM seasons) AS seasons, (SELECT COUNT(*) FROM players) AS players;"

echo "=== cost ==="
sudo -n docker stats --no-stream --format '{{.Name}} cpu={{.CPUPerc}} mem={{.MemUsage}}' "$NAME"
free -m | head -2
echo "MIGRATIONS COMPLETE"
echo "=== END ==="
