# deploy-server-properties.sh - GENERATED by scripts/gen-deploy-server-properties.ps1
# Do not edit by hand. Edit server/server.properties and regenerate.
# Template: 73 keys, 2 of them preserved from the live file: rcon.password, management-server-secret
#
# Installs the repository template onto the dev volume. Fails closed.

set -e

V=$(sudo -n ls -1 /var/lib/pelican/volumes | head -1)
D="/var/lib/pelican/volumes/$V"
LIVE="$D/server.properties"
BACKUP="$D/_quarantine/server.properties.prebuild"
OWN=999:987

TPL=$(mktemp)
NEW=$(mktemp)
LIVECOPY=$(mktemp)
KL=$(mktemp)
KT=$(mktemp)
trap 'rm -f "$TPL" "$NEW" "$LIVECOPY" "$KL" "$KT"' EXIT

echo "=== volume ==="
echo "$V"

# ---- 1. the container must be stopped --------------------------------------
# Paper reads server.properties at boot and REWRITES it at shutdown. Editing it
# under a running server means the running server overwrites the edit on stop.
echo "=== container must be stopped ==="
if sudo -n docker ps --format '{{.Names}}' | grep -q "$V"; then
  echo "ABORT: container is running. Paper rewrites server.properties at shutdown and would discard this deploy."
  exit 2
fi
echo "confirmed stopped"

# ---- 2. the live file must exist, and gets backed up once ------------------
if ! sudo -n test -f "$LIVE"; then
  echo "ABORT: no live server.properties at $LIVE. Refusing to guess which keys exist."
  exit 3
fi
sudo -n mkdir -p "$D/_quarantine"
if sudo -n test -f "$BACKUP"; then
  echo "pre-build backup already exists, keeping the original"
else
  sudo -n cp -p "$LIVE" "$BACKUP"
  sudo -n chown $OWN "$BACKUP"
  echo "saved $BACKUP  (stays on the host: it holds the live secrets and must never be copied off)"
fi
sudo -n cat "$LIVE" > "$LIVECOPY"

# ---- 3. the template ------------------------------------------------------
cat > "$TPL" <<'LT_SERVER_PROPERTIES_EOF'
# LaughTail SMP - server.properties
#
# This file is the SOURCE OF TRUTH (Section 29). It is deployed to the VPS by
# scripts/remote/deploy-server-properties.sh, never edited on the server.
#
# Secrets are NOT stored here. Any value written as __PRESERVE__ is read from the
# live file on the server and carried across, so no credential ever enters git
# (never-break rule 5, acceptance row 2).
#
# Every non-obvious value below cites the specification section that decides it.

# --- identity and access ------------------------------------------------------
motd=\u00A76\u00A7l\u2726 LAUGH TALE \u2726\u00A7r\\n\u00A7dWhere Legends Laugh
server-port=25565
server-ip=
# 0.3 and 6.4: online-mode is mandatory and is never disabled, for any reason.
online-mode=true
# 23: paid whitelist only. Nobody joins without paying.
white-list=true
enforce-whitelist=true
# 4.4: Bedrock clients cannot sign chat. Paper refuses them when this is true,
# so it is off and Floodgate handles platform identity instead.
enforce-secure-profile=false
prevent-proxy-connections=false
# 6.4 / 23: 24 initially, then set from measurement in Phase 6. Not a guess -
# a starting point that row 21 replaces with a measured number.
max-players=24
player-idle-timeout=0
# 7.2 allows elytra, and Paper's vanilla flight check exempts elytra gliding, so
# false does not ban elytra. 15.6 bans /fly as a feature at every rank forever,
# but that is a permission node, not this key. Left at the vanilla default so a
# crude backstop exists until GrimAC is proven to catch flight (row 50). Phase 1
# may set this true once that evidence exists, because a real anti-cheat does the
# check properly and the vanilla one can false-kick on a laggy tick.
allow-flight=false
# 1.21.9 vanilla feature: a code-of-conduct players must accept. It cannot
# satisfy row 17, which requires acceptance stored in the database WITH A VERSION,
# and it needs a code-of-conduct.txt present or the boot warns. Off until Phase 1
# builds the real gate. Revisit then as the display layer only.
enable-code-of-conduct=false

# --- world --------------------------------------------------------------------
# NOT "world". The pre-existing world/ directory on this host was generated by
# Minecraft 26.2 (DataVersion 4903) and Minecraft cannot downgrade a world.
# Pointing level-name elsewhere means Paper 1.21.11 never reads it, so the
# owner's existing world stays untouched and intact. See decisions.md D-0013.
level-name=laughtail
level-seed=
level-type=minecraft\:normal
generator-settings={}
generate-structures=true
max-world-size=29999984
allow-nether=true

# --- gameplay rules, all from Section 23 --------------------------------------
gamemode=survival
force-gamemode=false
difficulty=hard
hardcore=false
pvp=true
spawn-monsters=true
# 7.5: spawn is protected.
spawn-protection=16

# --- performance, Section 6.4 -------------------------------------------------
# 23: view 6, simulation 4. Lower than vanilla on purpose - this is a 2 vCPU box
# and these two values dominate the tick budget.
view-distance=6
simulation-distance=4
entity-broadcast-range-percentage=100
network-compression-threshold=256
# Paper's own hang detector. The four-step degradation ladder in 6.6 is separate
# and is built in Phase 6.
max-tick-time=60000
max-chained-neighbor-updates=1000000
sync-chunk-writes=false
region-file-compression=deflate
use-native-transport=true
# Phase 6 tuning candidate: a positive value idles the server when empty, which
# would conserve CPU credits on this burstable instance (progress.md R1). Left
# disabled for now because a paused server does not run scheduled tasks, and
# 31.1 puts the season reset on a clock. Re-evaluate with the load test.
pause-when-empty-seconds=-1

# --- moderation and evidence --------------------------------------------------
# Required by row 32: same-IP kills must award zero RP and raise an alert, which
# needs the IP recorded. Retention is governed by 31.13.
log-ips=true
chat-spam-threshold-seconds=10
command-spam-threshold-seconds=10
rate-limit=0
broadcast-console-to-ops=true
broadcast-rcon-to-ops=false
op-permission-level=4
function-permission-level=2

# --- rcon: local automation only ---------------------------------------------
# Row 5 requires RCON be unreachable externally. It is not exposed in ufw and
# not published by the container, so it is reachable only on the host.
enable-rcon=true
rcon.port=25575
rcon.password=__PRESERVE__

# --- management server: the OTHER remote-control surface, kept shut -----------
# Minecraft 1.21.9 added a management API. It is a second way to run commands on
# this server, so row 5 ("RCON unreachable, only the intended ports open") applies
# to it exactly as it does to RCON. It is disabled, bound to localhost, and given
# port 0 so nothing is listened on even if it were enabled by accident.
#
# The secret is PRESERVED rather than blanked or omitted. Omitting it would make
# Paper generate a new one at boot - a silent credential rotation, which is the
# kind of quiet change AGENTS.md says never to allow. It is 40 characters long and
# its value has never been read into this repository or an agent transcript.
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=__PRESERVE__
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
management-server-allowed-origins=

# --- resource pack: optional, never forced (23, row 61) ----------------------
resource-pack=
resource-pack-id=
resource-pack-sha1=
resource-pack-prompt=
require-resource-pack=false

# --- status and telemetry -----------------------------------------------------
enable-status=true
hide-online-players=false
enable-query=false
query.port=25565
enable-jmx-monitoring=false
debug=false
text-filtering-version=0
text-filtering-config=
# 0 = Paper's default heartbeat. Not a tuning knob; recorded so the key is not
# regenerated silently.
status-heartbeat-interval=0
initial-enabled-packs=vanilla
initial-disabled-packs=
accepts-transfers=false
bug-report-link=
LT_SERVER_PROPERTIES_EOF

# ---- 4. key parity: the template must not drop a key the live file has ------
# A dropped key is not left alone - Paper writes its default back at boot. For a
# secret that is a silent rotation, so this is a hard abort, not a warning.
grep -o '^[a-z0-9._-]*=' "$LIVECOPY" | tr -d '=' | sort -u > "$KL"
grep -o '^[a-z0-9._-]*=' "$TPL"      | tr -d '=' | sort -u > "$KT"
MISSING=$(comm -23 "$KL" "$KT")
ADDED=$(comm -13 "$KL" "$KT")
echo "=== key parity ==="
echo "live keys:     $(wc -l < "$KL")"
echo "template keys: $(wc -l < "$KT")"
if [ -n "$ADDED" ]; then
  echo "keys the template ADDS (fine - Paper accepts them):"
  echo "$ADDED" | sed 's/^/  + /'
fi
if [ -n "$MISSING" ]; then
  echo "ABORT: the template is MISSING keys that exist live. Paper would regenerate defaults for these:"
  echo "$MISSING" | sed 's/^/  - /'
  echo "Add them to server/server.properties deliberately, then regenerate this script."
  exit 4
fi
echo "parity OK: no key would be regenerated"

# ---- 5. carry the preserved values across, host-side only -------------------
echo "=== preserved values ==="
while IFS= read -r line || [ -n "$line" ]; do
  case "$line" in
    *=__PRESERVE__)
      k=${line%%=*}
      # Only "." needs escaping: the template parser only accepts keys matching
      # [a-z0-9._-], and of those characters "." is the sole regex metacharacter.
      kesc=$(printf '%s' "$k" | sed 's/\./\\./g')
      if ! grep -q "^${kesc}=" "$LIVECOPY"; then
        echo "ABORT: template asks to preserve $k but the live file has no such key."
        exit 5
      fi
      v=$(grep -m1 "^${kesc}=" "$LIVECOPY" | cut -d= -f2-)
      printf '%s=%s\n' "$k" "$v" >> "$NEW"
      echo "  preserved $k  (${#v} chars, value deliberately not shown)"
      ;;
    *)
      printf '%s\n' "$line" >> "$NEW"
      ;;
  esac
done < "$TPL"

# Anchored to an assignment, because the template's own comments explain what
# __PRESERVE__ means and a bare grep matches that prose too.
if grep -qE '^[a-z0-9._-]+=__PRESERVE__$' "$NEW"; then
  echo "ABORT: a __PRESERVE__ placeholder survived into the output. Installing nothing."
  exit 6
fi

# ---- 6. install, then fix ownership (the 33.1 ownership trap) ---------------
sudo -n cp "$NEW" "$LIVE"
sudo -n chown $OWN "$LIVE"
sudo -n chmod 644 "$LIVE"

echo "=== installed ==="
sudo -n stat -c 'owner=%u:%g mode=%a size=%s' "$LIVE"
echo "expected owner=999:987 mode=644"

# ---- 7. verify, with the two secret-bearing keys redacted -------------------
echo "=== deployed file, secrets redacted ==="
sudo -n sed -E 's/^(rcon\.password|management-server-secret|management-server-tls-keystore-password)=.*/\1=<redacted>/' "$LIVE"

echo "=== the values that decide acceptance rows, read back from disk ==="
for k in online-mode white-list enforce-whitelist enable-rcon rcon.port \
         management-server-enabled management-server-port level-name difficulty \
         pvp max-players view-distance simulation-distance spawn-protection log-ips; do
  printf '  %-28s %s\n' "$k" "$(sudo -n grep -m1 "^${k}=" "$LIVE" | cut -d= -f2-)"
done

echo "=== any unresolved placeholder ASSIGNMENT left in the file? ==="
if sudo -n grep -qE '^[a-z0-9._-]+=__PRESERVE__$' "$LIVE"; then echo "FAIL: placeholder present"; exit 7; fi
echo "none"
echo "SERVER.PROPERTIES DEPLOYED"
echo "=== END ==="
