# fetch-artefacts.sh - GENERATED by scripts/gen-fetch-artefacts.ps1
# Do not edit by hand. Regenerate from server/manifest.yml.
# Minecraft 26.2. Every checksum below is publisher-stated.
#
# Downloads into a staging directory. Installs nothing. Verifies everything.

STAGE=/home/ubuntu/laughtail-stage
mkdir -p "$STAGE"
cd "$STAGE"
FAIL=0

# ---- paper 26.2-119 ----
EXPECT="a8c9140c3075bd7c04973e9cdc491b21bfe6bad472b674ef932a4ae0fec19629"
FILE="paper-26.2-119.jar"
if [ -f "$FILE" ] && [ "$(sha256sum "$FILE" | cut -d" " -f1)" = "$EXPECT" ]; then
  echo "  cached+verified paper  $FILE"
else
  echo "  downloading paper  $FILE"
  curl -sSL --retry 3 --retry-delay 2 -o "$FILE" "https://fill-data.papermc.io/v1/objects/a8c9140c3075bd7c04973e9cdc491b21bfe6bad472b674ef932a4ae0fec19629/paper-26.2-119.jar"
  ACTUAL="$(sha256sum "$FILE" | cut -d" " -f1)"
  if [ "$ACTUAL" = "$EXPECT" ]; then
    echo "  OK   paper  sha256 verified"
  else
    echo "  FAIL paper  sha256 MISMATCH"
    echo "       expected $EXPECT"
    echo "       actual   $ACTUAL"
    rm -f "$FILE"
    FAIL=$((FAIL+1))
  fi
fi

# ---- geyser 2.11.2-b1232 ----
EXPECT="5a56d231221fbf7ad6d701f2a39581fff9b7835df28f1a6345a1b8cf34455b92"
FILE="Geyser-Spigot.jar"
if [ -f "$FILE" ] && [ "$(sha256sum "$FILE" | cut -d" " -f1)" = "$EXPECT" ]; then
  echo "  cached+verified geyser  $FILE"
else
  echo "  downloading geyser  $FILE"
  curl -sSL --retry 3 --retry-delay 2 -o "$FILE" "https://download.geysermc.org/v2/projects/geyser/versions/2.11.2/builds/1232/downloads/spigot"
  ACTUAL="$(sha256sum "$FILE" | cut -d" " -f1)"
  if [ "$ACTUAL" = "$EXPECT" ]; then
    echo "  OK   geyser  sha256 verified"
  else
    echo "  FAIL geyser  sha256 MISMATCH"
    echo "       expected $EXPECT"
    echo "       actual   $ACTUAL"
    rm -f "$FILE"
    FAIL=$((FAIL+1))
  fi
fi

# ---- floodgate 2.2.5-b140 ----
EXPECT="9f436c42ffd8b1091a437d7a4e16f82181b9d5314f8b1732dfa9d5a4fffb19fe"
FILE="floodgate-spigot.jar"
if [ -f "$FILE" ] && [ "$(sha256sum "$FILE" | cut -d" " -f1)" = "$EXPECT" ]; then
  echo "  cached+verified floodgate  $FILE"
else
  echo "  downloading floodgate  $FILE"
  curl -sSL --retry 3 --retry-delay 2 -o "$FILE" "https://download.geysermc.org/v2/projects/floodgate/versions/2.2.5/builds/140/downloads/spigot"
  ACTUAL="$(sha256sum "$FILE" | cut -d" " -f1)"
  if [ "$ACTUAL" = "$EXPECT" ]; then
    echo "  OK   floodgate  sha256 verified"
  else
    echo "  FAIL floodgate  sha256 MISMATCH"
    echo "       expected $EXPECT"
    echo "       actual   $ACTUAL"
    rm -f "$FILE"
    FAIL=$((FAIL+1))
  fi
fi

# ---- viaversion 5.11.0 ----
EXPECT="7cdb9443cc31cdd83a665cbd40222a45a364670323fbf031d7fe8c57c279932fe940c5db7b4fd3970b8f28491077f1be634213405c616f054c9cf31871016f79"
FILE="ViaVersion-5.11.0.jar"
if [ -f "$FILE" ] && [ "$(sha512sum "$FILE" | cut -d" " -f1)" = "$EXPECT" ]; then
  echo "  cached+verified viaversion  $FILE"
else
  echo "  downloading viaversion  $FILE"
  curl -sSL --retry 3 --retry-delay 2 -o "$FILE" "https://cdn.modrinth.com/data/P1OZGk5p/versions/ZH8459B6/ViaVersion-5.11.0.jar"
  ACTUAL="$(sha512sum "$FILE" | cut -d" " -f1)"
  if [ "$ACTUAL" = "$EXPECT" ]; then
    echo "  OK   viaversion  sha512 verified"
  else
    echo "  FAIL viaversion  sha512 MISMATCH"
    echo "       expected $EXPECT"
    echo "       actual   $ACTUAL"
    rm -f "$FILE"
    FAIL=$((FAIL+1))
  fi
fi

# ---- viabackwards 5.11.0 ----
EXPECT="85ab6b2444c17e6777f5bb7adb3c492e616451972d2a7989914e82b4714d82da2a5901b97f3b49b0f4e0ba2e5468f4799a1354157b2d955327ea256f307c82ca"
FILE="ViaBackwards-5.11.0.jar"
if [ -f "$FILE" ] && [ "$(sha512sum "$FILE" | cut -d" " -f1)" = "$EXPECT" ]; then
  echo "  cached+verified viabackwards  $FILE"
else
  echo "  downloading viabackwards  $FILE"
  curl -sSL --retry 3 --retry-delay 2 -o "$FILE" "https://cdn.modrinth.com/data/NpvuJQoq/versions/hYhg2QBT/ViaBackwards-5.11.0.jar"
  ACTUAL="$(sha512sum "$FILE" | cut -d" " -f1)"
  if [ "$ACTUAL" = "$EXPECT" ]; then
    echo "  OK   viabackwards  sha512 verified"
  else
    echo "  FAIL viabackwards  sha512 MISMATCH"
    echo "       expected $EXPECT"
    echo "       actual   $ACTUAL"
    rm -f "$FILE"
    FAIL=$((FAIL+1))
  fi
fi

# ---- luckperms v5.5.71-bukkit ----
EXPECT="188a91f0a543d23bfda32385fca6db63d61e49c8a422bd452a260bd9cbc6a7d7fe45071199e9fca8f3ce43c2b41ee84fd315bd15464577028ff3951a7d4fab27"
FILE="LuckPerms-Bukkit-5.5.71.jar"
if [ -f "$FILE" ] && [ "$(sha512sum "$FILE" | cut -d" " -f1)" = "$EXPECT" ]; then
  echo "  cached+verified luckperms  $FILE"
else
  echo "  downloading luckperms  $FILE"
  curl -sSL --retry 3 --retry-delay 2 -o "$FILE" "https://cdn.modrinth.com/data/Vebnzrzj/versions/b0mk8uS6/LuckPerms-Bukkit-5.5.71.jar"
  ACTUAL="$(sha512sum "$FILE" | cut -d" " -f1)"
  if [ "$ACTUAL" = "$EXPECT" ]; then
    echo "  OK   luckperms  sha512 verified"
  else
    echo "  FAIL luckperms  sha512 MISMATCH"
    echo "       expected $EXPECT"
    echo "       actual   $ACTUAL"
    rm -f "$FILE"
    FAIL=$((FAIL+1))
  fi
fi

# ---- chunky 1.5.3 ----
EXPECT="43ffecc6e6a734b752da41575bbb316526c124c3f878942437d5133c377bfbd9b78bda975520dc074d7158c15dade58a444ccd0fd8d8a25d165b6fc450140422"
FILE="Chunky-Bukkit-1.5.3.jar"
if [ -f "$FILE" ] && [ "$(sha512sum "$FILE" | cut -d" " -f1)" = "$EXPECT" ]; then
  echo "  cached+verified chunky  $FILE"
else
  echo "  downloading chunky  $FILE"
  curl -sSL --retry 3 --retry-delay 2 -o "$FILE" "https://cdn.modrinth.com/data/fALzjamp/versions/MdY6JATr/Chunky-Bukkit-1.5.3.jar"
  ACTUAL="$(sha512sum "$FILE" | cut -d" " -f1)"
  if [ "$ACTUAL" = "$EXPECT" ]; then
    echo "  OK   chunky  sha512 verified"
  else
    echo "  FAIL chunky  sha512 MISMATCH"
    echo "       expected $EXPECT"
    echo "       actual   $ACTUAL"
    rm -f "$FILE"
    FAIL=$((FAIL+1))
  fi
fi

# ---- grimac 2.3.74-961fa54 ----
EXPECT="bf9be1194eb45afe1dec6bd8e98d078dacf41539025c8aabe24d31337cbea86625774e30842568b47f34ca174472c724c7876cc30793945e7408b03609672655"
FILE="grimac-bukkit-2.3.74-961fa54.jar"
if [ -f "$FILE" ] && [ "$(sha512sum "$FILE" | cut -d" " -f1)" = "$EXPECT" ]; then
  echo "  cached+verified grimac  $FILE"
else
  echo "  downloading grimac  $FILE"
  curl -sSL --retry 3 --retry-delay 2 -o "$FILE" "https://cdn.modrinth.com/data/LJNGWSvH/versions/1FIGlM6Q/grimac-bukkit-2.3.73.jar"
  ACTUAL="$(sha512sum "$FILE" | cut -d" " -f1)"
  if [ "$ACTUAL" = "$EXPECT" ]; then
    echo "  OK   grimac  sha512 verified"
  else
    echo "  FAIL grimac  sha512 MISMATCH"
    echo "       expected $EXPECT"
    echo "       actual   $ACTUAL"
    rm -f "$FILE"
    FAIL=$((FAIL+1))
  fi
fi

# ---- simple-voice-chat bukkit-2.6.21 ----
EXPECT="12a0ff0240e12bda82c10f2277c7bf3016c2a1833f8e73f338a61601cb555a2b18832041c902c81c4f8dd781993994fbd60d0336f443d92ff887933141a6f5a7"
FILE="voicechat-bukkit-2.6.21.jar"
if [ -f "$FILE" ] && [ "$(sha512sum "$FILE" | cut -d" " -f1)" = "$EXPECT" ]; then
  echo "  cached+verified simple-voice-chat  $FILE"
else
  echo "  downloading simple-voice-chat  $FILE"
  curl -sSL --retry 3 --retry-delay 2 -o "$FILE" "https://cdn.modrinth.com/data/9eGKb6K1/versions/62MVmInV/voicechat-bukkit-2.6.21.jar"
  ACTUAL="$(sha512sum "$FILE" | cut -d" " -f1)"
  if [ "$ACTUAL" = "$EXPECT" ]; then
    echo "  OK   simple-voice-chat  sha512 verified"
  else
    echo "  FAIL simple-voice-chat  sha512 MISMATCH"
    echo "       expected $EXPECT"
    echo "       actual   $ACTUAL"
    rm -f "$FILE"
    FAIL=$((FAIL+1))
  fi
fi

echo "=== staged files ==="
ls -lh "$STAGE"
echo "=== disk ==="
df -h --output=avail / | tail -1
echo "failures: $FAIL"
if [ "$FAIL" -ne 0 ]; then echo "ARTEFACT FETCH FAILED - installing nothing"; exit 1; fi
echo "ALL ARTEFACTS VERIFIED ON HOST"
