# verify-permissions.sh - GENERATED by scripts/gen-permissions.ps1 from verify-permissions.template.sh. Do not edit by hand.
# Carries 31 never-grant nodes from server/permissions.yml.
# verify-permissions.sh - acceptance 17.5. READ ONLY apart from writing an export.
#
# WHY THIS DOES NOT USE `lp permission check`. It did, and the result was a FALSE
# PASS. LuckPerms processes commands asynchronously and returns nothing to an RCON
# sender, so all 31 checks came back empty - and a verdict computed as "no line
# said true" then reported PASS against no output whatsoever. That is worse than no
# check: it manufactures evidence. Never-break rule 11 wants evidence, and silence
# is not evidence.
#
# So instead: `lp export` writes an authoritative snapshot of every group, node and
# inheritance edge, and that file is analysed. This is also what Appendix C asks to
# keep in version control ("permissions export ... in version control").
#
# The analysis resolves inheritance itself rather than trusting a single group's
# node list, because a denial on `admin` is worthless if a parent grants the node
# and LuckPerms' resolution order is misunderstood. The rule applied is LuckPerms'
# own: a value set on the group itself wins over anything inherited, and among
# inherited values the nearer ancestor wins.

set -e

V=$(sudo -n ls -1 /var/lib/pelican/volumes | head -1)
D="/var/lib/pelican/volumes/$V"
LP="$D/plugins/LuckPerms"
CIP=$(sudo -n docker inspect "$V" --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}')

if ! sudo -n docker ps --format '{{.Names}}' | grep -q "$V"; then
  echo "ABORT: the server is not running."
  exit 2
fi

echo "=== asking LuckPerms for an export ==="
sudo -n rm -f "$LP/lt-verify.json.gz" "$LP/lt-verify.json"

cat > /tmp/lt-lpx.py <<'PYEOF'
import socket, struct, sys
PROPS, HOST = sys.argv[1], sys.argv[2]
pw, port = None, 25575
with open(PROPS, 'r', encoding='utf-8', errors='replace') as f:
    for line in f:
        if line.startswith('rcon.password='):
            pw = line.split('=', 1)[1].strip()
        elif line.startswith('rcon.port='):
            port = int(line.split('=', 1)[1].strip())
def pkt(rid, typ, body):
    p = struct.pack('<ii', rid, typ) + body.encode() + b'\x00\x00'
    return struct.pack('<i', len(p)) + p
s = socket.create_connection((HOST, port), timeout=20)
s.settimeout(25)
s.sendall(pkt(1, 3, pw))
s.recv(4096)
for cmd in sys.argv[3:]:
    s.sendall(pkt(2, 2, cmd))
    try:
        s.recv(4096)
    except socket.timeout:
        pass
s.close()
print('export requested')
PYEOF
sudo -n python3 /tmp/lt-lpx.py "$D/server.properties" "$CIP" "lp export lt-verify"
sudo -n rm -f /tmp/lt-lpx.py

echo "=== waiting for the export file (up to 30s) ==="
EXPORT=""
for i in $(seq 1 15); do
  for cand in "$LP/lt-verify.json.gz" "$LP/lt-verify.json"; do
    if sudo -n test -s "$cand"; then EXPORT="$cand"; break; fi
  done
  [ -n "$EXPORT" ] && break
  sleep 2
done

if [ -z "$EXPORT" ]; then
  echo "ABORT: LuckPerms produced no export. Cannot verify 17.5, and will NOT report a pass"
  echo "       on the strength of missing output - that is how a false pass happens."
  sudo -n ls -la "$LP" 2>/dev/null | head -20
  exit 3
fi
echo "export: $EXPORT ($(sudo -n stat -c %s "$EXPORT") bytes)"

cat > /tmp/lt-lpcheck.py <<'PYEOF'
import gzip, json, sys, io

path = sys.argv[1]
opener = gzip.open if path.endswith('.gz') else open
with opener(path, 'rt', encoding='utf-8') as f:
    data = json.load(f)

groups = data.get('groups', {})
if not groups:
    print('ABORT: the export contains no groups at all')
    sys.exit(4)

# node name -> value, per group; plus parent edges
own = {}
parents = {}
for gname, gdata in groups.items():
    own[gname] = {}
    parents[gname] = []
    for n in gdata.get('nodes', []):
        key = n.get('key', '')
        val = n.get('value', True)
        if key.startswith('group.'):
            if val:
                parents[gname].append(key[len('group.'):])
        else:
            own[gname][key] = val

def chain(g, seen=None):
    """Group itself first, then nearer ancestors before further ones."""
    if seen is None:
        seen = set()
    if g in seen:
        return []
    seen.add(g)
    out = [g]
    for p in parents.get(g, []):
        out.extend(chain(p, seen))
    return out

def effective(group, node):
    """LuckPerms resolution: a value on the group itself wins; otherwise the
    nearest ancestor that defines it wins. Wildcards are checked too, because '*'
    set to true on any ancestor would grant everything."""
    for g in chain(group):
        if node in own.get(g, {}):
            return own[g][node], g
        if own.get(g, {}).get('*', False) is True:
            return True, g + ' (via wildcard *)'
    return None, None

print('=== group tree from the export ===')
for g in sorted(groups, key=lambda x: x):
    print('  %-10s parents=%-20s own nodes=%d' % (g, ','.join(parents.get(g, [])) or '-', len(own.get(g, {}))))

NEVER = [l.strip() for l in open('/tmp/lt-never.txt', encoding='utf-8') if l.strip()]

print()
print('=== 17.5 item 1: the admin group against every never-grant node ===')
fails = []
for node in NEVER:
    val, src = effective('admin', node)
    if val is True:
        state = 'GRANTED  <-- FAIL'
        fails.append((node, src))
    elif val is False:
        state = 'denied explicitly on ' + src
    else:
        state = 'undefined (not granted anywhere in the chain)'
    print('  %-40s %s' % (node, state))

print()
print('nodes checked: %d   granted: %d' % (len(NEVER), len(fails)))
if fails:
    print('17.5 ITEM 1 FAIL - an Admin can do something on the never-grant list:')
    for n, s in fails:
        print('    %s  granted by %s' % (n, s))
else:
    print('17.5 ITEM 1 PASS - the admin group holds none of the %d never-grant nodes,' % len(NEVER))
    print('                   verified one by one against the export, with inheritance resolved')

print()
print('=== 17.5 item 2: inheritance matrix ===')
MATRIX = [
    ('helper', 'laughtail.report.view',      True,  'a Helper has its own node'),
    ('helper', 'laughtail.punish.tempban',   False, 'a Helper must NOT have a Mod node'),
    ('helper', 'laughtail.player.basic',     True,  'inherited from default'),
    ('mod',    'laughtail.report.view',      True,  'inherited from helper'),
    ('admin',  'laughtail.report.view',      True,  'inherited down the whole chain'),
    ('admin',  'laughtail.reload',           True,  '17.2 lets an Admin reload the LaughTail config'),
    ('admin',  'minecraft.command.reload',   False, '17.3 forbids reloading the SERVER - different node'),
    ('admin',  'laughtail.season.reset',     False, 'never-grant'),
    ('owner',  'laughtail.season.reset',     True,  'the Owner has everything, explicitly not by wildcard'),
    ('owner',  'laughtail.audit.read',       True,  'Owner only'),
    ('admin',  'laughtail.rollback.preview', True,  '17.2 grants PREVIEW to an Admin'),
    ('admin',  'coreprotect.rollback',       False, 'but not the rollback itself'),
]
mfail = 0
for group, node, expect, why in MATRIX:
    val, src = effective(group, node)
    got = (val is True)
    ok = (got == expect)
    if not ok:
        mfail += 1
    print('  %-6s %-32s expect=%-5s got=%-5s %s   %s'
          % (group, node, expect, got, 'ok' if ok else 'FAIL', why))
print()
print('matrix rows: %d   failures: %d' % (len(MATRIX), mfail))
if mfail == 0:
    print('17.5 ITEM 2 PASS - inheritance verified by a test matrix, not by assumption')
else:
    print('17.5 ITEM 2 FAIL')

print()
print('=== wildcard audit: nobody below owner may hold "*" ===')
wfail = 0
for g in sorted(groups):
    v = own.get(g, {}).get('*', None)
    if v is True:
        print('  %-10s HOLDS the wildcard  <-- FAIL (17.3 forbids it)' % g)
        wfail += 1
    elif v is False:
        print('  %-10s wildcard explicitly denied' % g)
if wfail == 0:
    print('  no group holds a wildcard')

print()
print('=== operator sanity: every node the Owner MUST hold to run the server ===')
# THIS CHECK EXISTS BECAUSE THE MATRIX ABOVE WAS NOT ENOUGH. It only tested nodes that were
# explicitly granted, so it could not notice one that was missing entirely - which is exactly
# how /laughtail rating came to reply "No permission" for the Owner.
#
# The cause is worth stating because it generalises: `admin` carries an explicit `* = false`
# (17.3 forbids a wildcard for Admin), `owner` inherits admin, and in LuckPerms an explicit
# wildcard denial beats an op-based default. So `default: op` in plugin.yml grants NOTHING once
# a wildcard denial exists anywhere in the chain, and every node must be granted by name.
#
# This list is therefore the set of things that must be true for the server to be operable at
# all. If any of them is false, the Owner cannot run their own server.
MUST_HOLD = [
    'laughtail.status',            # /laughtail status and /laughtail rating
    'laughtail.reload',            # /laughtail reload - the replacement for vanilla /reload
    'laughtail.season.reset',      # /season
    'laughtail.whitelist.add',     # /access grant - the paywall
    'laughtail.whitelist.remove',  # /access revoke
    'laughtail.punish.permban',    # /ban
    'laughtail.punish.history',    # /history
    'laughtail.punish.overturn',   # /unban
    'laughtail.rules.bypass',      # the Owner is not held by their own rules gate
    'laughtail.audit.read',        # reading the audit trail
]
ofail = 0
for node in MUST_HOLD:
    val, src = effective('owner', node)
    ok = (val is True)
    if not ok:
        ofail += 1
    print('  %-30s owner=%-5s %s%s' % (node, val, 'ok' if ok else 'FAIL',
        '' if ok else '   <-- the Owner cannot use this'))
print()
if ofail == 0:
    print('OPERATOR SANITY PASS - the Owner holds all %d nodes needed to run the server' % len(MUST_HOLD))
else:
    print('OPERATOR SANITY FAIL - %d node(s) the Owner needs are not granted.' % ofail)
    print('Grant them by name in server/permissions.yml. Relying on `default: op` does not')
    print('work once any group in the chain denies the wildcard.')

total = len(fails) + mfail + wfail + ofail
print()
print('TOTAL FAILURES: %d' % total)
sys.exit(1 if total else 0)
PYEOF

# The never-grant list, written from the repository so the check cannot drift from
# server/permissions.yml.
sudo -n tee /tmp/lt-never.txt > /dev/null <<'LT_NEVER_EOF'
*
luckperms.*
luckperms.user.permission.set
luckperms.group.permission.set
minecraft.command.op
minecraft.command.deop
minecraft.command.stop
bukkit.command.stop
minecraft.command.reload
bukkit.command.reload
laughtail.plugins.manage
plugman.*
laughtail.economy.set
laughtail.economy.reset
laughtail.economy.price
coreprotect.rollback
coreprotect.restore
coreprotect.purge
laughtail.backup.run
laughtail.backup.restore
laughtail.db.access
laughtail.season.reset
laughtail.season.champion
worldedit.*
fawe.*
minecraft.command.whitelist
bukkit.command.whitelist
laughtail.whitelist.add
laughtail.whitelist.remove
laughtail.audit.read
laughtail.secrets.read
LT_NEVER_EOF

sudo -n python3 /tmp/lt-lpcheck.py "$EXPORT"
RC=$?
sudo -n rm -f /tmp/lt-lpcheck.py /tmp/lt-never.txt
echo "=== END (exit $RC) ==="
exit $RC
