# gen-schedule-backups.ps1 - emits scripts/remote/schedule-backups.sh with
# scripts/remote/backup-run.sh embedded, so cron gets a real file at a stable path
# instead of depending on something in /tmp or a home directory.
#
# Same one-source rule as the other generators: backup-run.sh is edited, this is
# regenerated, and the two cannot drift.

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repo = Split-Path -Parent $PSScriptRoot
$srcBackup = Join-Path $repo 'scripts\remote\backup-run.sh'
$dest = Join-Path $repo 'scripts\remote\schedule-backups.sh'

if (-not (Test-Path -LiteralPath $srcBackup)) { throw "Missing $srcBackup" }
$backupLines = Get-Content -LiteralPath $srcBackup

$marker = 'LT_BACKUP_SCRIPT_EOF'
if ($backupLines | Where-Object { $_.Trim() -eq $marker }) {
  throw "backup-run.sh contains the heredoc marker. Refusing to generate."
}
if (-not ($backupLines | Where-Object { $_ -match '--db-only' })) {
  throw "backup-run.sh does not handle --db-only, but the hourly cron entry passes it. Refusing to generate a schedule that would fail every hour."
}

$o = New-Object System.Collections.Generic.List[string]
$a = { param($s) $o.Add($s) }

& $a '# schedule-backups.sh - GENERATED by scripts/gen-schedule-backups.ps1.'
& $a '# Do not edit by hand. Edit scripts/remote/backup-run.sh and regenerate.'
& $a '#'
& $a '# Puts the backup on a timer. Spec 5.4 wants hourly database and six-hourly world'
& $a '# backups; until now nothing ran them, and an unscheduled backup script is'
& $a '# documentation rather than a backup.'
& $a '#'
& $a '# WHY /etc/cron.d AND NOT `crontab -e`: a file in /etc/cron.d has a path, an owner'
& $a '# and a mode, so it can be read, diffed and audited by anyone who later inherits'
& $a '# this box. A user crontab lives in a spool directory nobody thinks to look in.'
& $a '#'
& $a '# WHY THE SCHEDULE IS SPLIT: backup-run.sh does both halves, but the world tar is'
& $a '# the expensive part - 213 MB of gzip - and this instance is BURSTABLE (R1).'
& $a '# Twenty-four world tars a day would spend CPU credits on data that changes far'
& $a '# less than the ledger does. So the hourly run passes --db-only and the'
& $a '# six-hourly run does everything.'
& $a '#'
& $a '# Times are offset from :00 so a CPU burst does not collide with every other job'
& $a '# on the box that also likes round numbers.'
& $a ''
& $a 'set -e'
& $a ''
& $a 'BIN=/usr/local/sbin/laughtail-backup.sh'
& $a 'CRON=/etc/cron.d/laughtail-backup'
& $a 'LOG=/var/log/laughtail-backup.log'
& $a ''
& $a 'echo "=== writing the backup script to a stable path ==="'
& $a '# cron must not depend on a script in /tmp or a home directory.'
& $a ("sudo -n tee ""`$BIN"" > /dev/null <<'{0}'" -f $marker)
foreach ($l in $backupLines) { & $a $l }
& $a $marker
& $a 'sudo -n chown root:root "$BIN"'
& $a 'sudo -n chmod 750 "$BIN"'
& $a 'sudo -n stat -c ''  %n owner=%U:%G mode=%a size=%s'' "$BIN"'
& $a ''
& $a 'echo "=== syntax check before scheduling it ==="'
& $a '# A cron job that fails at 03:17 with a syntax error is discovered days later.'
& $a 'if sudo -n bash -n "$BIN"; then echo "  bash -n: OK"; else echo "  ABORT: syntax error"; exit 3; fi'
& $a ''
& $a 'echo "=== writing the cron file ==="'
& $a 'sudo -n tee "$CRON" > /dev/null <<''LT_CRON_EOF'''
& $a '# LaughTail SMP backups. Managed by scripts/remote/schedule-backups.sh.'
& $a '# Do not edit by hand - regenerate from the repository.'
& $a '#'
& $a '# Spec 5.4: hourly database, six-hourly world.'
& $a 'SHELL=/bin/bash'
& $a 'PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin'
& $a ''
& $a '# Database only, every hour at :17'
& $a '17 * * * * root /usr/local/sbin/laughtail-backup.sh --db-only >> /var/log/laughtail-backup.log 2>&1'
& $a ''
& $a '# Full backup including the world, every six hours at :23'
& $a '23 */6 * * * root /usr/local/sbin/laughtail-backup.sh >> /var/log/laughtail-backup.log 2>&1'
& $a 'LT_CRON_EOF'
& $a 'sudo -n chown root:root "$CRON"'
& $a 'sudo -n chmod 644 "$CRON"'
& $a ''
& $a 'echo "=== cron IGNORES a file in /etc/cron.d that is group or world writable ==="'
& $a '# This is the classic silent failure: the file looks right, cron never runs it.'
& $a 'sudo -n stat -c ''  %n owner=%U:%G mode=%a'' "$CRON"'
& $a 'MODE=$(sudo -n stat -c %a "$CRON")'
& $a 'if [ "$MODE" = "644" ]; then echo "  mode OK"; else echo "  WARNING: mode $MODE - cron may ignore this file"; fi'
& $a ''
& $a 'echo "=== log file and rotation, so the log cannot fill a 19 GB disk ==="'
& $a 'sudo -n touch "$LOG"'
& $a 'sudo -n chown root:root "$LOG"'
& $a 'sudo -n chmod 640 "$LOG"'
& $a 'sudo -n tee /etc/logrotate.d/laughtail-backup > /dev/null <<''LT_LR_EOF'''
& $a '/var/log/laughtail-backup.log {'
& $a '    weekly'
& $a '    rotate 4'
& $a '    compress'
& $a '    missingok'
& $a '    notifempty'
& $a '    copytruncate'
& $a '}'
& $a 'LT_LR_EOF'
& $a '# NOT piped to head: the runner sets `set -o pipefail`, and head closing the pipe'
& $a '# early sends SIGPIPE to logrotate, which surfaces as exit 141 and aborts the'
& $a '# whole script under set -e. Capture first, then trim.'
& $a 'sudo -n logrotate --debug /etc/logrotate.d/laughtail-backup > /tmp/lt-lr.txt 2>&1 || true'
& $a 'head -6 /tmp/lt-lr.txt'
& $a 'rm -f /tmp/lt-lr.txt'
& $a ''
& $a 'echo "=== is cron actually running? ==="'
& $a 'systemctl is-active cron 2>/dev/null || systemctl is-active crond 2>/dev/null || echo "WARNING: no cron service is active - nothing will run"'
& $a ''
& $a 'echo "=== proving the scheduled command works, by running the hourly one now ==="'
& $a '# Scheduling something that has never run is how you find out at 03:17 that it'
& $a '# does not. This runs exactly what cron will run, as root, the same way.'
& $a 'sudo -n "$BIN" --db-only 2>&1 | tail -18'
& $a ''
& $a 'echo "=== installed schedule ==="'
& $a 'sudo -n grep -vE ''^\s*#|^\s*$|^[A-Z]+='' "$CRON"'
& $a 'echo "SCHEDULE INSTALLED"'
& $a 'echo "=== END ==="'

Set-Content -LiteralPath $dest -Value $o -Encoding UTF8
Write-Output ("wrote scripts/remote/schedule-backups.sh ({0} lines, embedding {1} lines of backup-run.sh)" -f $o.Count, $backupLines.Count)
