# gen-schedule-monitor.ps1 - emits scripts/remote/schedule-monitor.sh with
# scripts/remote/monitor.sh embedded, so cron runs a real file at a stable path.
#
# Same reasoning as gen-schedule-backups.ps1: one source, regenerated, cannot drift.

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repo = Split-Path -Parent $PSScriptRoot
$src  = Join-Path $repo 'scripts\remote\monitor.sh'
$dest = Join-Path $repo 'scripts\remote\schedule-monitor.sh'
if (-not (Test-Path -LiteralPath $src)) { throw "Missing $src" }

$lines = Get-Content -LiteralPath $src
$marker = 'LT_MONITOR_EOF'
if ($lines | Where-Object { $_.Trim() -eq $marker }) { throw 'monitor.sh contains the heredoc marker' }

$o = New-Object System.Collections.Generic.List[string]
$a = { param($s) $o.Add($s) }

& $a '# schedule-monitor.sh - GENERATED by scripts/gen-schedule-monitor.ps1.'
& $a '# Do not edit by hand. Edit scripts/remote/monitor.sh and regenerate.'
& $a '#'
& $a '# Phase 0.7. Every five minutes: is the server up, is the database up, is the tick'
& $a '# rate healthy, is memory or disk running out, is the last backup recent, and have'
& $a '# new errors appeared.'
& $a '#'
& $a '# WHY FIVE MINUTES and not one: each sample opens an RCON connection and runs three'
& $a '# commands. That is cheap but not free, and this instance is burstable (R1). Five'
& $a '# minutes is 288 samples a day, enough to see a degradation trend and to notice an'
& $a '# outage quickly, without the monitoring becoming a load of its own. The in-game'
& $a '# 6.6 watchdog is what reacts within a tick; this is not trying to be that.'
& $a ''
& $a 'set -e'
& $a 'BIN=/usr/local/sbin/laughtail-monitor.sh'
& $a 'CRON=/etc/cron.d/laughtail-monitor'
& $a 'LOG=/var/log/laughtail-monitor.log'
& $a ''
& $a 'echo "=== writing the monitor to a stable path ==="'
& $a ("sudo -n tee ""`$BIN"" > /dev/null <<'{0}'" -f $marker)
foreach ($l in $lines) { & $a $l }
& $a $marker
& $a 'sudo -n chown root:root "$BIN"'
& $a 'sudo -n chmod 750 "$BIN"'
& $a 'sudo -n stat -c ''  %n owner=%U:%G mode=%a size=%s'' "$BIN"'
& $a ''
& $a 'echo "=== syntax check before scheduling ==="'
& $a 'if sudo -n bash -n "$BIN"; then echo "  bash -n: OK"; else echo "  ABORT: syntax error"; exit 3; fi'
& $a ''
& $a 'echo "=== cron file ==="'
& $a 'sudo -n tee "$CRON" > /dev/null <<''LT_CRON_EOF'''
& $a '# LaughTail SMP monitoring. Managed by scripts/remote/schedule-monitor.sh.'
& $a '# Do not edit by hand - regenerate from the repository.'
& $a 'SHELL=/bin/bash'
& $a 'PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin'
& $a ''
& $a '*/5 * * * * root /usr/local/sbin/laughtail-monitor.sh >> /var/log/laughtail-monitor.log 2>&1'
& $a 'LT_CRON_EOF'
& $a 'sudo -n chown root:root "$CRON"'
& $a 'sudo -n chmod 644 "$CRON"'
& $a 'MODE=$(sudo -n stat -c %a "$CRON")'
& $a 'echo "  mode $MODE (must be 644 or cron ignores the file silently)"'
& $a ''
& $a 'echo "=== rotation ==="'
& $a 'sudo -n touch "$LOG"; sudo -n chown root:root "$LOG"; sudo -n chmod 640 "$LOG"'
& $a 'sudo -n tee /etc/logrotate.d/laughtail-monitor > /dev/null <<''LT_LR_EOF'''
& $a '/var/log/laughtail-monitor.log {'
& $a '    daily'
& $a '    rotate 7'
& $a '    compress'
& $a '    missingok'
& $a '    notifempty'
& $a '    copytruncate'
& $a '}'
& $a 'LT_LR_EOF'
& $a 'echo "  logrotate config written (daily, 7 kept - a 5-minute sampler is chatty)"'
& $a ''
& $a 'echo "=== proving the scheduled command runs, exactly as cron will ==="'
& $a 'sudo -n "$BIN" 2>&1 | tail -12'
& $a ''
& $a 'echo "=== cron service ==="'
& $a 'systemctl is-active cron 2>/dev/null || echo "WARNING: cron is not active"'
& $a 'echo "MONITOR SCHEDULED"'
& $a 'echo "=== END ==="'

Set-Content -LiteralPath $dest -Value $o -Encoding UTF8
Write-Output ("wrote scripts/remote/schedule-monitor.sh ({0} lines, embedding {1} lines of monitor.sh)" -f $o.Count, $lines.Count)
