# gen-db-migrate.ps1 - reads db/migrations/*.sql and emits
# scripts/remote/db-migrate.sh with every migration embedded in a quoted heredoc.
#
# Same reasoning as gen-deploy-server-properties.ps1: the SQL has to reach the host
# somehow, and a heredoc keeps the generated script reviewable in git - unlike a
# base64 blob - while keeping exactly one copy of the truth so the two cannot drift.
#
# Checksums are computed ON THE HOST, never here. A checksum taken on Windows would
# be of CRLF content and would never match the LF content that actually lands on the
# server, so every run would look like tampering.

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repo = Split-Path -Parent $PSScriptRoot
$migDir = Join-Path $repo 'db\migrations'
$dest = Join-Path $repo 'scripts\remote\db-migrate.sh'

$files = @(Get-ChildItem -LiteralPath $migDir -Filter 'V*.sql' | Sort-Object {
    if ($_.Name -match '^V(\d+)__') { [int]$Matches[1] } else { 999999 }
  })
if ($files.Count -eq 0) { throw "No migrations found in $migDir" }

foreach ($f in $files) {
  if ($f.Name -notmatch '^V(\d+)__(.+)\.sql$') {
    throw "Migration '$($f.Name)' does not match V<number>__<description>.sql"
  }
}

$o = New-Object System.Collections.Generic.List[string]
$a = { param($s) $o.Add($s) }

& $a '# db-migrate.sh - GENERATED by scripts/gen-db-migrate.ps1. Do not edit by hand.'
& $a '# Edit db/migrations/*.sql and regenerate.'
& $a ('# Carries {0} migration(s): {1}' -f $files.Count, (($files | ForEach-Object { $_.Name }) -join ', '))
& $a '#'
& $a '# Applies pending migrations in version order and records a SHA-256 of each file'
& $a '# as applied.'
& $a '#'
& $a '# FORWARD-ONLY IS ENFORCED, NOT REQUESTED. If an already-applied migration has a'
& $a '# different checksum now, the run ABORTS and applies nothing. Appendix D says'
& $a '# never modify a live schema by hand; the corollary is never modify an applied'
& $a '# migration, because the database cannot be re-derived from it afterwards. Without'
& $a '# a checksum an edited V1 is indistinguishable from an untouched one.'
& $a '#'
& $a '# Runs as the APP user, not root: full rights on the laughtail database and none'
& $a '# outside it, so a mistake in a migration cannot reach the Panel data or the mysql'
& $a '# system tables. Passwords are read inside the container and never printed.'
& $a ''
& $a 'set -e'
& $a ''
& $a 'NAME=laughtail-db'
& $a 'DB=laughtail'
& $a 'WORK=/home/ubuntu/laughtail-db/migrations'
& $a ''
& $a 'if ! sudo -n docker ps --format ''{{.Names}}'' | grep -qx "$NAME"; then'
& $a '  echo "ABORT: the $NAME container is not running. Start it with db-up.sh."'
& $a '  exit 2'
& $a 'fi'
& $a ''
& $a 'sudo -n mkdir -p "$WORK"'
& $a ''
& $a '# Helper: run SQL as the app user. Password never appears in argv or output.'
& $a '#'
& $a '# The output is captured and filtered with sed, NOT piped through grep. Piping to'
& $a '# grep makes the pipeline exit status grep''s: a statement like CREATE TABLE'
& $a '# produces no output, grep finds nothing, exits 1, and under set -e the whole run'
& $a '# aborts on a statement that actually succeeded. The real mariadb exit status has'
& $a '# to survive, because the row 36 test depends on distinguishing success from a'
& $a '# constraint violation.'
& $a 'q() {'
& $a '  local out rc'
& $a '  out=$(sudo -n docker exec -u root "$NAME" sh -c "mariadb -u $DB -p\"\$(cat /run/lt-secrets/app_password)\" -D $DB -N -B -e \"$1\"" 2>&1)'
& $a '  rc=$?'
& $a '  printf ''%s\n'' "$out" | sed ''/password on the command line/d'''
& $a '  return $rc'
& $a '}'
& $a ''
& $a '# Helper: run a whole file as the app user.'
& $a 'qfile() {'
& $a '  local out rc'
& $a '  out=$(sudo -n docker exec -i -u root "$NAME" sh -c "mariadb -u $DB -p\"\$(cat /run/lt-secrets/app_password)\" -D $DB" < "$1" 2>&1)'
& $a '  rc=$?'
& $a '  printf ''%s\n'' "$out" | sed ''/password on the command line/d'''
& $a '  return $rc'
& $a '}'
& $a ''
& $a 'echo "=== connectivity ==="'
& $a 'q "SELECT VERSION() AS version, DATABASE() AS db, @@time_zone AS tz;"'
& $a ''

# ---- write each migration to the work directory -----------------------------
foreach ($f in $files) {
  $name = $f.Name
  $marker = 'LT_SQL_EOF_' + ($name -replace '[^A-Za-z0-9]', '_')
  $lines = Get-Content -LiteralPath $f.FullName
  if ($lines | Where-Object { $_.Trim() -eq $marker }) {
    throw "Migration $name contains its own heredoc marker. Refusing to generate."
  }
  & $a ('# ---- stage {0} ----' -f $name)
  & $a ("sudo -n tee ""`$WORK/{0}"" > /dev/null <<'{1}'" -f $name, $marker)
  foreach ($l in $lines) { & $a $l }
  & $a $marker
  & $a ''
}

& $a 'echo "=== bootstrap: the bookkeeping table must exist before anything is recorded ==="'
& $a '# Chicken and egg: schema_migrations is created BY V1, but V1 must be recorded IN'
& $a '# it. So the table is created idempotently here first. V1 also declares it with'
& $a '# CREATE TABLE IF NOT EXISTS, so applying V1 on a fresh database still works and'
& $a '# the definition stays in version control where it belongs.'
& $a 'q "CREATE TABLE IF NOT EXISTS schema_migrations (version VARCHAR(20) NOT NULL, description VARCHAR(200) NOT NULL, checksum CHAR(64) NOT NULL, applied_at DATETIME(3) NOT NULL, applied_by VARCHAR(100) NOT NULL, duration_ms INT UNSIGNED NOT NULL, PRIMARY KEY (version)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;"'
& $a ''
& $a 'echo "=== checking already-applied migrations for tampering ==="'
& $a 'DRIFT=0'
& $a 'PENDING=""'
& $a ''

foreach ($f in $files) {
  $name = $f.Name
  if ($name -match '^V(\d+)__(.+)\.sql$') {
    $ver = 'V' + $Matches[1]
    $desc = ($Matches[2] -replace '_', ' ')
  }
  & $a ('# ---- {0} ----' -f $name)
  & $a ('SUM=$(sudo -n sha256sum "$WORK/{0}" | cut -d" " -f1)' -f $name)
  & $a ('REC=$(q "SELECT checksum FROM schema_migrations WHERE version=''{0}'';" | tr -dc ''0-9a-f'')' -f $ver)
  & $a 'if [ -z "$REC" ]; then'
  & $a ('  echo "  {0} PENDING"' -f $name)
  & $a ('  PENDING="$PENDING {0}"' -f $name)
  & $a 'elif [ "$REC" = "$SUM" ]; then'
  & $a ('  echo "  {0} already applied, checksum matches"' -f $name)
  & $a 'else'
  & $a ('  echo "  {0} ALREADY APPLIED BUT CHECKSUM DIFFERS"' -f $name)
  & $a '  echo "    recorded: $REC"'
  & $a '  echo "    now:      $SUM"'
  & $a '  DRIFT=$((DRIFT + 1))'
  & $a 'fi'
  & $a ''
}

& $a 'if [ "$DRIFT" -ne 0 ]; then'
& $a '  echo "ABORT: $DRIFT applied migration(s) have been edited. Applying nothing."'
& $a '  echo "Migrations are forward-only. Add a new V<n> instead of changing an old one."'
& $a '  exit 3'
& $a 'fi'
& $a ''
& $a 'if [ -z "$PENDING" ]; then'
& $a '  echo "=== nothing to apply. Schema is up to date. ==="'
& $a 'else'
& $a '  echo "=== applying:$PENDING ==="'
& $a 'fi'
& $a ''

foreach ($f in $files) {
  $name = $f.Name
  if ($name -match '^V(\d+)__(.+)\.sql$') {
    $ver = 'V' + $Matches[1]
    $desc = ($Matches[2] -replace '_', ' ')
  }
  & $a ('case "$PENDING" in *{0}*)' -f $name)
  & $a ('  echo "--- applying {0} ---"' -f $name)
  & $a '  START=$(date +%s%3N)'
  & $a ('  if qfile "$WORK/{0}"; then' -f $name)
  & $a '    END=$(date +%s%3N)'
  & $a ('    SUM=$(sudo -n sha256sum "$WORK/{0}" | cut -d" " -f1)' -f $name)
  & $a ('    q "INSERT INTO schema_migrations (version, description, checksum, applied_at, applied_by, duration_ms) VALUES (''{0}'', ''{1}'', ''$SUM'', UTC_TIMESTAMP(3), ''db-migrate.sh'', $((END - START)));"' -f $ver, $desc)
  & $a ('    echo "  applied {0} in $((END - START)) ms"' -f $name)
  & $a '  else'
  & $a ('    echo "  FAILED: {0} did not apply. Not recording it."' -f $name)
  & $a '    exit 4'
  & $a '  fi'
  & $a '  ;;'
  & $a 'esac'
  & $a ''
}

& $a 'echo "=== resulting schema ==="'
& $a 'q "SELECT TABLE_NAME, ENGINE, TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA=''laughtail'' ORDER BY TABLE_NAME;"'
& $a ''
& $a 'echo "=== migration history ==="'
& $a 'q "SELECT version, description, applied_at, duration_ms FROM schema_migrations ORDER BY version;"'
& $a ''
& $a 'echo "=== ACCEPTANCE ROW 36: the one-champion-per-season guarantee ==="'
& $a '# Row 36 demands evidence of "schema plus failed-insert test". A passing test'
& $a '# here means the DATABASE refuses a second champion, so no application bug, race'
& $a '# or manual console command can produce two. Application-level checking would'
& $a '# satisfy the wording and miss the point.'
& $a 'q "INSERT IGNORE INTO players (uuid, current_name, first_join, last_seen, created_at, updated_at) VALUES (''00000000-0000-4000-8000-000000000001'', ''RowThirtySix'', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));"'
& $a 'q "INSERT IGNORE INTO seasons (season_number, starts_at, ends_at, state, created_at, updated_at) VALUES (99999, UTC_TIMESTAMP(3), UTC_TIMESTAMP(3), ''archived'', UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));"'
& $a 'q "INSERT IGNORE INTO champions (season_number, uuid, final_rp, awarded_at, created_at) VALUES (99999, ''00000000-0000-4000-8000-000000000001'', 2000, UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));"'
& $a 'echo "first champion for test season 99999:"'
& $a 'q "SELECT COUNT(*) AS champions_for_season FROM champions WHERE season_number=99999;"'
& $a ''
& $a 'echo "now attempting a SECOND champion for the same season - this MUST fail:"'
& $a 'SECOND=$(q "INSERT INTO champions (season_number, uuid, final_rp, awarded_at, created_at) VALUES (99999, ''00000000-0000-4000-8000-000000000001'', 9999, UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));" || true)'
& $a 'echo "  database said: $SECOND"'
& $a 'if echo "$SECOND" | grep -qi ''duplicate entry''; then'
& $a '  echo "  ROW 36 PASS: the database refused the second champion."'
& $a 'else'
& $a '  echo "  ROW 36 FAIL: the second insert was NOT refused. The constraint is not doing its job."'
& $a 'fi'
& $a 'q "SELECT COUNT(*) AS still_only_one FROM champions WHERE season_number=99999;"'
& $a ''
& $a 'echo "=== cleaning up the test rows ==="'
& $a 'q "DELETE FROM champions WHERE season_number=99999;"'
& $a 'q "DELETE FROM seasons WHERE season_number=99999;"'
& $a 'q "DELETE FROM players WHERE uuid=''00000000-0000-4000-8000-000000000001'';"'
& $a 'q "SELECT (SELECT COUNT(*) FROM champions) AS champions, (SELECT COUNT(*) FROM seasons) AS seasons, (SELECT COUNT(*) FROM players) AS players;"'
& $a ''
& $a 'echo "=== cost ==="'
& $a 'sudo -n docker stats --no-stream --format ''{{.Name}} cpu={{.CPUPerc}} mem={{.MemUsage}}'' "$NAME"'
& $a 'free -m | head -2'
& $a 'echo "MIGRATIONS COMPLETE"'
& $a 'echo "=== END ==="'

Set-Content -LiteralPath $dest -Value $o -Encoding UTF8
Write-Output ("wrote scripts/remote/db-migrate.sh ({0} lines) carrying {1} migration(s)" -f $o.Count, $files.Count)
$files | ForEach-Object { Write-Output ("  " + $_.Name) }
