# gen-deploy-server-properties.ps1 - reads server/server.properties (the source of
# truth, Section 29) and emits scripts/remote/deploy-server-properties.sh.
#
# Why a generator rather than a hand-written deploy script: the template has to
# travel to the host somehow. Embedding it in a quoted heredoc keeps the generated
# script fully reviewable in git - unlike a base64 blob - and keeps exactly one
# copy of the truth, so the two can never drift.
#
# The generated script does four things the template alone cannot:
#
#   1. Refuses to run while the container is up. server.properties is read once at
#      boot and rewritten at shutdown, so editing it on a running server loses the
#      edit silently. That is the failure mode AGENTS.md warns about most.
#   2. Carries every __PRESERVE__ value across from the live file, host-side. No
#      credential is ever transmitted, printed or written into the repository
#      (never-break rule 5, acceptance row 2).
#   3. Aborts if the template is missing any key the live file has. Paper
#      regenerates a default for a missing key, which for a secret is a silent
#      credential rotation.
#   4. Fixes ownership afterwards - the 33.1 ownership trap.
#
# Fail closed at every step: any doubt exits non-zero and installs nothing.

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repo = Split-Path -Parent $PSScriptRoot
$src  = Join-Path $repo 'server\server.properties'
$dest = Join-Path $repo 'scripts\remote\deploy-server-properties.sh'

if (-not (Test-Path -LiteralPath $src)) { throw "Missing $src" }

$template = Get-Content -LiteralPath $src

# ---- refuse to generate if the template could break the heredoc --------------
$marker = 'LT_SERVER_PROPERTIES_EOF'
if ($template | Where-Object { $_.Trim() -eq $marker }) {
  throw "The template contains the heredoc marker '$marker'. Refusing to generate a script that would truncate."
}

# ---- refuse to generate if a real secret is sitting in the template ----------
# The whole point of __PRESERVE__ is that these keys never hold a value in git.
$secretKeys = @('rcon.password', 'management-server-secret', 'management-server-tls-keystore-password')
foreach ($line in $template) {
  foreach ($k in $secretKeys) {
    if ($line -match ('^' + [regex]::Escape($k) + '=(.*)$')) {
      $v = $Matches[1]
      if ($v -ne '' -and $v -ne '__PRESERVE__') {
        throw "SECRET IN TEMPLATE: '$k' has a literal value in server/server.properties. Replace it with __PRESERVE__ before committing (never-break rule 5)."
      }
    }
  }
}

$keys      = @($template | ForEach-Object { if ($_ -match '^([a-z0-9._-]+)=') { $Matches[1] } })
$preserved = @($template | ForEach-Object { if ($_ -match '^([a-z0-9._-]+)=__PRESERVE__$') { $Matches[1] } })

$o = New-Object System.Collections.Generic.List[string]
$a = { param($s) $o.Add($s) }

& $a '# deploy-server-properties.sh - GENERATED by scripts/gen-deploy-server-properties.ps1'
& $a '# Do not edit by hand. Edit server/server.properties and regenerate.'
& $a ('# Template: {0} keys, {1} of them preserved from the live file: {2}' -f $keys.Count, $preserved.Count, ($preserved -join ', '))
& $a '#'
& $a '# Installs the repository template onto the dev volume. Fails closed.'
& $a ''
& $a 'set -e'
& $a ''
& $a 'V=$(sudo -n ls -1 /var/lib/pelican/volumes | head -1)'
& $a 'D="/var/lib/pelican/volumes/$V"'
& $a 'LIVE="$D/server.properties"'
& $a 'BACKUP="$D/_quarantine/server.properties.prebuild"'
& $a 'OWN=999:987'
& $a ''
& $a 'TPL=$(mktemp)'
& $a 'NEW=$(mktemp)'
& $a 'LIVECOPY=$(mktemp)'
& $a 'KL=$(mktemp)'
& $a 'KT=$(mktemp)'
& $a 'trap ''rm -f "$TPL" "$NEW" "$LIVECOPY" "$KL" "$KT"'' EXIT'
& $a ''
& $a 'echo "=== volume ==="'
& $a 'echo "$V"'
& $a ''
& $a '# ---- 1. the container must be stopped --------------------------------------'
& $a '# Paper reads server.properties at boot and REWRITES it at shutdown. Editing it'
& $a '# under a running server means the running server overwrites the edit on stop.'
& $a 'echo "=== container must be stopped ==="'
& $a 'if sudo -n docker ps --format ''{{.Names}}'' | grep -q "$V"; then'
& $a '  echo "ABORT: container is running. Paper rewrites server.properties at shutdown and would discard this deploy."'
& $a '  exit 2'
& $a 'fi'
& $a 'echo "confirmed stopped"'
& $a ''
& $a '# ---- 2. the live file must exist, and gets backed up once ------------------'
& $a 'if ! sudo -n test -f "$LIVE"; then'
& $a '  echo "ABORT: no live server.properties at $LIVE. Refusing to guess which keys exist."'
& $a '  exit 3'
& $a 'fi'
& $a 'sudo -n mkdir -p "$D/_quarantine"'
& $a 'if sudo -n test -f "$BACKUP"; then'
& $a '  echo "pre-build backup already exists, keeping the original"'
& $a 'else'
& $a '  sudo -n cp -p "$LIVE" "$BACKUP"'
& $a '  sudo -n chown $OWN "$BACKUP"'
& $a '  echo "saved $BACKUP  (stays on the host: it holds the live secrets and must never be copied off)"'
& $a 'fi'
& $a 'sudo -n cat "$LIVE" > "$LIVECOPY"'
& $a ''
& $a '# ---- 3. the template ------------------------------------------------------'
& $a ("cat > ""`$TPL"" <<'{0}'" -f $marker)
foreach ($line in $template) { & $a $line }
& $a $marker
& $a ''
& $a '# ---- 4. key parity: the template must not drop a key the live file has ------'
& $a '# A dropped key is not left alone - Paper writes its default back at boot. For a'
& $a '# secret that is a silent rotation, so this is a hard abort, not a warning.'
& $a 'grep -o ''^[a-z0-9._-]*='' "$LIVECOPY" | tr -d ''='' | sort -u > "$KL"'
& $a 'grep -o ''^[a-z0-9._-]*='' "$TPL"      | tr -d ''='' | sort -u > "$KT"'
& $a 'MISSING=$(comm -23 "$KL" "$KT")'
& $a 'ADDED=$(comm -13 "$KL" "$KT")'
& $a 'echo "=== key parity ==="'
& $a 'echo "live keys:     $(wc -l < "$KL")"'
& $a 'echo "template keys: $(wc -l < "$KT")"'
& $a 'if [ -n "$ADDED" ]; then'
& $a '  echo "keys the template ADDS (fine - Paper accepts them):"'
& $a '  echo "$ADDED" | sed ''s/^/  + /'''
& $a 'fi'
& $a 'if [ -n "$MISSING" ]; then'
& $a '  echo "ABORT: the template is MISSING keys that exist live. Paper would regenerate defaults for these:"'
& $a '  echo "$MISSING" | sed ''s/^/  - /'''
& $a '  echo "Add them to server/server.properties deliberately, then regenerate this script."'
& $a '  exit 4'
& $a 'fi'
& $a 'echo "parity OK: no key would be regenerated"'
& $a ''
& $a '# ---- 5. carry the preserved values across, host-side only -------------------'
& $a 'echo "=== preserved values ==="'
& $a 'while IFS= read -r line || [ -n "$line" ]; do'
& $a '  case "$line" in'
& $a '    *=__PRESERVE__)'
& $a '      k=${line%%=*}'
& $a '      # Only "." needs escaping: the template parser only accepts keys matching'
& $a '      # [a-z0-9._-], and of those characters "." is the sole regex metacharacter.'
& $a '      kesc=$(printf ''%s'' "$k" | sed ''s/\./\\./g'')'
& $a '      if ! grep -q "^${kesc}=" "$LIVECOPY"; then'
& $a '        echo "ABORT: template asks to preserve $k but the live file has no such key."'
& $a '        exit 5'
& $a '      fi'
& $a '      v=$(grep -m1 "^${kesc}=" "$LIVECOPY" | cut -d= -f2-)'
& $a '      printf ''%s=%s\n'' "$k" "$v" >> "$NEW"'
& $a '      echo "  preserved $k  (${#v} chars, value deliberately not shown)"'
& $a '      ;;'
& $a '    *)'
& $a '      printf ''%s\n'' "$line" >> "$NEW"'
& $a '      ;;'
& $a '  esac'
& $a 'done < "$TPL"'
& $a ''
& $a '# Anchored to an assignment, because the template''s own comments explain what'
& $a '# __PRESERVE__ means and a bare grep matches that prose too.'
& $a 'if grep -qE ''^[a-z0-9._-]+=__PRESERVE__$'' "$NEW"; then'
& $a '  echo "ABORT: a __PRESERVE__ placeholder survived into the output. Installing nothing."'
& $a '  exit 6'
& $a 'fi'
& $a ''
& $a '# ---- 6. install, then fix ownership (the 33.1 ownership trap) ---------------'
& $a 'sudo -n cp "$NEW" "$LIVE"'
& $a 'sudo -n chown $OWN "$LIVE"'
& $a 'sudo -n chmod 644 "$LIVE"'
& $a ''
& $a 'echo "=== installed ==="'
& $a 'sudo -n stat -c ''owner=%u:%g mode=%a size=%s'' "$LIVE"'
& $a 'echo "expected owner=999:987 mode=644"'
& $a ''
& $a '# ---- 7. verify, with the two secret-bearing keys redacted -------------------'
& $a 'echo "=== deployed file, secrets redacted ==="'
& $a 'sudo -n sed -E ''s/^(rcon\.password|management-server-secret|management-server-tls-keystore-password)=.*/\1=<redacted>/'' "$LIVE"'
& $a ''
& $a 'echo "=== the values that decide acceptance rows, read back from disk ==="'
& $a 'for k in online-mode white-list enforce-whitelist enable-rcon rcon.port \'
& $a '         management-server-enabled management-server-port level-name difficulty \'
& $a '         pvp max-players view-distance simulation-distance spawn-protection log-ips; do'
& $a '  printf ''  %-28s %s\n'' "$k" "$(sudo -n grep -m1 "^${k}=" "$LIVE" | cut -d= -f2-)"'
& $a 'done'
& $a ''
& $a 'echo "=== any unresolved placeholder ASSIGNMENT left in the file? ==="'
& $a 'if sudo -n grep -qE ''^[a-z0-9._-]+=__PRESERVE__$'' "$LIVE"; then echo "FAIL: placeholder present"; exit 7; fi'
& $a 'echo "none"'
& $a 'echo "SERVER.PROPERTIES DEPLOYED"'
& $a 'echo "=== END ==="'

Set-Content -LiteralPath $dest -Value $o -Encoding UTF8
Write-Output ("wrote scripts/remote/deploy-server-properties.sh ({0} lines)" -f $o.Count)
Write-Output ("template: {0} keys, {1} preserved: {2}" -f $keys.Count, $preserved.Count, ($preserved -join ', '))

# ---- second output: the drift checker ---------------------------------------
# Paper REWRITES server.properties at boot and strips every comment. Measured
# 2026-08-26: the deployed file went from 6,155 bytes and ~60 comment lines to
# 1,868 bytes and 2. So a byte-comparison drift detector would report drift after
# every single start, which trains everyone to ignore it.
#
# Drift is therefore defined on MEANING, not bytes: same keys, same values,
# comments ignored, and the two preserved secrets compared as "still non-empty"
# rather than by value.
$driftDest = Join-Path $repo 'scripts\remote\check-properties-drift.sh'
$d = New-Object System.Collections.Generic.List[string]
$da = { param($s) $d.Add($s) }

& $da '# check-properties-drift.sh - GENERATED by scripts/gen-deploy-server-properties.ps1'
& $da '# Do not edit by hand. READ ONLY: changes nothing, reports only.'
& $da '#'
& $da '# Compares the LIVE server.properties against the repository template by KEY and'
& $da '# VALUE. Comments and key order are ignored, because Paper strips comments and'
& $da '# reorders keys every time it boots - so a byte diff is guaranteed to be noisy'
& $da '# and would be ignored within a week.'
& $da '#'
& $da '# The two preserved secrets are compared as "non-empty", never by value.'
& $da ''
& $da 'V=$(sudo -n ls -1 /var/lib/pelican/volumes | head -1)'
& $da 'LIVE="/var/lib/pelican/volumes/$V/server.properties"'
& $da 'TPL=$(mktemp); A=$(mktemp); B=$(mktemp)'
& $da 'trap ''rm -f "$TPL" "$A" "$B"'' EXIT'
& $da ''
& $da ("cat > ""`$TPL"" <<'{0}'" -f $marker)
foreach ($line in $template) { & $da $line }
& $da $marker
& $da ''
& $da '# Strip comments and blanks, sort, and blank out the secret VALUES on both sides.'
& $da '#'
& $da '# motd is compared separately. The repository writes it as \uXXXX escapes, which'
& $da '# is the portable way to put section signs in a Java properties file, and Paper'
& $da '# decodes them to literal UTF-8 when it rewrites the file. The two spellings are'
& $da '# the same string, so comparing them raw reports drift that does not exist.'
& $da 'normalise() {'
& $da '  grep -E ''^[a-z0-9._-]+='' "$1" \'
& $da '    | sed -E ''s/^(rcon\.password|management-server-secret|management-server-tls-keystore-password)=.*/\1=<compared-separately>/'' \'
& $da '    | sed -E ''s/^motd=.*/motd=<compared-separately>/'' \'
& $da '    | sort'
& $da '}'
& $da ''
& $da 'sudo -n cat "$LIVE" > "$B.raw"'
& $da 'normalise "$TPL"    > "$A"'
& $da 'normalise "$B.raw"  > "$B"'
& $da ''
& $da 'echo "=== drift: repository template vs live server.properties ==="'
& $da 'echo "template keys: $(wc -l < "$A")   live keys: $(wc -l < "$B")"'
& $da 'if diff -u "$A" "$B" > /dev/null; then'
& $da '  echo "NO DRIFT: every key and value matches the repository."'
& $da 'else'
& $da '  echo "DRIFT DETECTED - lines prefixed - are the repository, + are the live server:"'
& $da '  diff -u "$A" "$B" | grep -E ''^[+-][a-z]'' || true'
& $da 'fi'
& $da ''
& $da 'echo "=== the preserved secrets must still be non-empty ==="'
& $da 'RC=0'
& $da 'for k in rcon.password management-server-secret; do'
& $da '  kesc=$(printf ''%s'' "$k" | sed ''s/\./\\./g'')'
& $da '  LEN=$(grep -m1 "^${kesc}=" "$B.raw" | cut -d= -f2- | tr -d ''\n'' | wc -c)'
& $da '  if [ "$LEN" -gt 0 ]; then'
& $da '    echo "  OK   $k is set ($LEN chars, value not shown)"'
& $da '  else'
& $da '    echo "  FAIL $k is EMPTY - a secret was lost or regenerated"'
& $da '    RC=1'
& $da '  fi'
& $da 'done'
& $da ''
& $da 'echo "=== motd: the repository escapes must mean the same as the live value ==="'
& $da 'T_MOTD=$(grep -m1 ''^motd='' "$TPL"   | cut -d= -f2-)'
& $da 'L_MOTD=$(grep -m1 ''^motd='' "$B.raw" | cut -d= -f2-)'
& $da 'if command -v python3 >/dev/null 2>&1; then'
& $da '  # Both sides are decoded with the SAME two Java .properties rules:'
& $da '  #   \uXXXX -> the character,  \\ -> a single backslash'
& $da '  # Note python''s own unicode_escape codec is wrong for this job: it decodes'
& $da '  # via latin-1, so a literal UTF-8 section sign on the live side comes back as'
& $da '  # two mojibake characters and the comparison fails for no real reason.'
& $da '  MATCH=$(T="$T_MOTD" L="$L_MOTD" python3 -c "'
& $da 'import os, re'
& $da 'def dec(s):'
& $da '    s = re.sub(r\"\\\\u([0-9a-fA-F]{4})\", lambda m: chr(int(m.group(1), 16)), s)'
& $da '    return s.replace(\"\\\\\\\\\", \"\\\\\")'
& $da 't, l = dec(os.environ[\"T\"]), dec(os.environ[\"L\"])'
& $da 'print(\"SAME\" if t == l else \"DIFF\")'
& $da 'print(t)'
& $da 'print(l)'
& $da '")'
& $da '  if [ "$(printf ''%s'' "$MATCH" | head -1)" = "SAME" ]; then'
& $da '    echo "  OK   template and live motd decode to the same string:"'
& $da '    printf ''%s'' "$MATCH" | sed -n ''2p'' | sed ''s/^/       /'''
& $da '  else'
& $da '    echo "  DRIFT in motd:"'
& $da '    printf ''%s'' "$MATCH" | sed -n ''2,3p'' | sed ''s/^/       /'''
& $da '    RC=1'
& $da '  fi'
& $da 'else'
& $da '  echo "  SKIPPED: python3 absent, cannot decode escapes. Not claiming a pass."'
& $da '  RC=1'
& $da 'fi'
& $da 'rm -f "$B.raw"'
& $da 'echo "=== END ==="'
& $da 'exit $RC'

Set-Content -LiteralPath $driftDest -Value $d -Encoding UTF8
Write-Output ("wrote scripts/remote/check-properties-drift.sh ({0} lines)" -f $d.Count)
