# gen-build-plugin.ps1 - emits:
#   scripts/remote/build-plugin.sh          - ships the source and builds it
#   scripts/remote/deploy-plugin-config.sh  - config with the DB secret injected
#
# WHY THE SOURCE TRAVELS AS HEREDOCS. Spec 30 says build on the VPS, and the host is
# aarch64 while this PC is not - so a locally built artefact could not be trusted
# even if a JDK were installed here. The source has to reach the host somehow, and
# heredocs keep the generated script reviewable in git, which a base64 blob would not.
#
# WHY MAVEN RUNS IN A CONTAINER. Never-break rule 13 and 33.2 item 4: do not install
# host packages mid-build without a snapshot, and OA-03 means none exists. A throwaway
# maven container needs nothing on the host. Same reasoning as D-0023 for MariaDB.

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repo = Split-Path -Parent $PSScriptRoot
$pluginDir = Join-Path $repo 'plugin'

$files = @(
  'pom.xml',
  'src/main/resources/plugin.yml',
  'src/main/resources/config.yml',
  'src/main/java/gg/laughtail/core/LaughTailPlugin.java',
  'src/main/java/gg/laughtail/core/Database.java',
  'src/main/java/gg/laughtail/core/RulesGate.java',
  'src/main/java/gg/laughtail/core/WorldRules.java',
  'src/main/java/gg/laughtail/core/StatsTracker.java',
  'src/main/java/gg/laughtail/core/CombatTracker.java',
  'src/main/java/gg/laughtail/core/Moderation.java',
  'src/main/java/gg/laughtail/core/AccessGrants.java',
  'src/main/java/gg/laughtail/core/Rating.java',
  'src/main/java/gg/laughtail/core/Economy.java',
  'src/main/java/gg/laughtail/core/Homes.java',
  'src/main/java/gg/laughtail/core/Teleports.java',
  'src/main/java/gg/laughtail/core/ResourceWorldGuard.java',
  'src/main/java/gg/laughtail/core/Menu.java',
  'src/main/java/gg/laughtail/core/Hud.java',
  'src/main/java/gg/laughtail/core/Shop.java',
  'src/main/java/gg/laughtail/core/Arbitrage.java',
  'src/main/java/gg/laughtail/core/ShopService.java',
  'src/main/java/gg/laughtail/core/SellBox.java',
  'src/main/java/gg/laughtail/core/CombatTag.java',
  'src/main/java/gg/laughtail/core/Social.java',
  'src/main/java/gg/laughtail/core/OrderBook.java',
  'src/main/java/gg/laughtail/core/Market.java',
  'src/main/java/gg/laughtail/core/SeasonScheduler.java',
  'src/main/java/gg/laughtail/core/Path.java',
  'src/main/java/gg/laughtail/core/Roleplay.java'
)

foreach ($f in $files) {
  $p = Join-Path $pluginDir ($f -replace '/', '\')
  if (-not (Test-Path -LiteralPath $p)) { throw "Missing plugin source file: $f" }
}

# Read the version out of the pom so the install step does not guess the jar name.
$pomText = Get-Content -LiteralPath (Join-Path $pluginDir 'pom.xml') -Raw
if ($pomText -notmatch '<artifactId>laughtail-core</artifactId>\s*<version>([^<]+)</version>') {
  throw 'Could not read the plugin version from pom.xml'
}
$version = $Matches[1]

$o = New-Object System.Collections.Generic.List[string]
$a = { param($s) $o.Add($s) }

& $a '# build-plugin.sh - GENERATED by scripts/gen-build-plugin.ps1. Do not edit.'
& $a '# Edit the sources under plugin/ and regenerate.'
& $a '#'
& $a ('# Builds LaughTail {0} from source, on the host, in a throwaway maven container.' -f $version)
& $a '#'
& $a '# Nothing is installed on the host: no JDK, no Maven. Never-break rule 13 and'
& $a '# 33.2 item 4 both say not to, and OA-03 means there is no snapshot to recover'
& $a '# from if a host package install went wrong.'
& $a ''
& $a 'set -e'
& $a ''
& $a 'SRC=/home/ubuntu/laughtail-plugin'
& $a 'M2=/home/ubuntu/.m2'
& $a 'IMAGE=maven:3.9-eclipse-temurin-25'
& $a ('VERSION={0}' -f $version)
& $a 'V=$(sudo -n ls -1 /var/lib/pelican/volumes | head -1)'
& $a 'D="/var/lib/pelican/volumes/$V"'
& $a 'OWN=999:987'
& $a ''
& $a 'echo "=== disk before (a maven cache is not small) ==="'
& $a 'df -h --output=avail,pcent / | tail -1'
& $a ''
& $a 'mkdir -p "$SRC" "$M2"'
& $a '# Literal path, not "$SRC/target": the guard refuses a recursive delete whose'
& $a '# target is a variable, because a static check cannot know what it expands to.'
& $a '# Removes only generated output, never the sources written below.'
& $a 'sudo -n rm -rf /home/ubuntu/laughtail-plugin/target'
& $a '# Ownership: maven used to run as root in the container, which left root-owned'
& $a '# output that the ubuntu user then could not clear on the next build. It now runs'
& $a '# as the host user (see the docker run below), so this only matters once.'
& $a 'sudo -n chown -R ubuntu:ubuntu /home/ubuntu/laughtail-plugin /home/ubuntu/.m2 2>/dev/null || true'
& $a 'mkdir -p "$SRC/src/main/java/gg/laughtail/core" "$SRC/src/main/resources"'
& $a ''

foreach ($f in $files) {
  $p = Join-Path $pluginDir ($f -replace '/', '\')
  $lines = Get-Content -LiteralPath $p
  $marker = 'LT_SRC_EOF_' + ($f -replace '[^A-Za-z0-9]', '_')
  if ($lines | Where-Object { $_.Trim() -eq $marker }) { throw "File $f contains its marker" }
  & $a ('# ---- {0} ----' -f $f)
  & $a ("cat > ""`$SRC/{0}"" <<'{1}'" -f $f, $marker)
  foreach ($l in $lines) { & $a $l }
  & $a $marker
  & $a ''
}

& $a 'echo "=== source staged ==="'
& $a 'find "$SRC/src" "$SRC/pom.xml" -type f | sort | while read -r f; do'
& $a '  echo "  $(wc -l < "$f" | tr -d " ") lines  ${f#$SRC/}"'
& $a 'done'
& $a ''
& $a 'echo "=== is the image present, and is it the right architecture? ==="'
& $a 'sudo -n docker pull "$IMAGE" 2>&1 | tail -2'
& $a 'sudo -n docker inspect "$IMAGE" --format ''arch={{.Architecture}}'''
& $a ''
& $a 'echo "=== compiling ==="'
& $a '# --memory 640m: this box has roughly 300 MB spare with the server running'
& $a '# (baselines.md B3), so an unbounded maven JVM could push the host into OOM and'
& $a '# take the game server with it. Capped deliberately, and the cap is generous'
& $a '# enough for a six-file project.'
& $a '#'
& $a '# The .m2 cache is mounted so a rebuild does not re-download the world - the'
& $a '# first build fetches Paper API and the MariaDB driver, later ones do not.'
& $a 'set +e'
& $a 'sudo -n docker run --rm \'
& $a '  --memory 640m --memory-swap 640m \'
& $a '  --cpus 1.5 \'
& $a '  -u "$(id -u ubuntu):$(id -g ubuntu)" \'
& $a '  -e HOME=/var/maven \'
& $a '  -e MAVEN_CONFIG=/var/maven/.m2 \'
& $a '  -v "$SRC":/src \'
& $a '  -v "$M2":/var/maven/.m2 \'
& $a '  -w /src \'
& $a '  "$IMAGE" mvn -B -q -DskipTests -Dmaven.repo.local=/var/maven/.m2/repository package 2>&1 | tail -30'
& $a 'RC=${PIPESTATUS[0]}'
& $a 'set -e'
& $a 'echo "maven exit: $RC"'
& $a 'if [ "$RC" -ne 0 ]; then'
& $a '  echo "BUILD FAILED - installing nothing."'
& $a '  exit 3'
& $a 'fi'
& $a ''
& $a 'JAR="$SRC/target/LaughTail-$VERSION.jar"'
& $a 'if [ ! -s "$JAR" ]; then'
& $a '  echo "BUILD REPORTED SUCCESS BUT THERE IS NO JAR - refusing to continue."'
& $a '  ls -la "$SRC/target" 2>/dev/null | head'
& $a '  exit 4'
& $a 'fi'
& $a 'echo "=== built ==="'
& $a 'ls -l "$JAR" | sed ''s/^/  /'''
& $a 'sha256sum "$JAR" | sed ''s/^/  /'''
& $a ''
& $a 'echo "=== the jar must contain the plugin descriptor and the shaded driver ==="'
& $a '# `jar tf`, not `unzip -l`: the maven image ships a JDK but no unzip, and the'
& $a '# first version of this check died on that after a successful build.'
& $a 'sudo -n docker run --rm -v "$SRC":/src -w /src "$IMAGE" \'
& $a '  sh -c "jar tf target/LaughTail-$VERSION.jar | grep -E ''^plugin.yml$|^config.yml$|LaughTailPlugin.class|RulesGate.class|Database.class|gg/laughtail/libs/mariadb/'' | head -8"'
& $a 'echo "--- driver classes shaded and relocated: ---"'
& $a 'sudo -n docker run --rm -v "$SRC":/src -w /src "$IMAGE" \'
& $a '  sh -c "jar tf target/LaughTail-$VERSION.jar | grep -c ''^gg/laughtail/libs/mariadb/''"'
& $a 'echo "--- and NO unrelocated org/mariadb (0 expected, or the relocation silently failed): ---"'
& $a 'sudo -n docker run --rm -v "$SRC":/src -w /src "$IMAGE" \'
& $a '  sh -c "jar tf target/LaughTail-$VERSION.jar | grep -c ''^org/mariadb/'' || true"'
& $a ''
& $a 'echo "=== installing into the server ==="'
& $a '# The old jar is replaced, not left beside the new one - two versions of the'
& $a '# same plugin in plugins/ is a load-order coin toss.'
& $a 'sudo -n rm -f "$D/plugins"/LaughTail-*.jar'
& $a 'sudo -n cp "$JAR" "$D/plugins/LaughTail-$VERSION.jar"'
& $a 'sudo -n chown $OWN "$D/plugins/LaughTail-$VERSION.jar"'
& $a 'sudo -n chmod 644 "$D/plugins/LaughTail-$VERSION.jar"'
& $a 'sudo -n ls -l "$D/plugins" | grep -i laughtail | sed ''s/^/  /'''
& $a ''
& $a 'echo "=== disk after ==="'
& $a 'df -h --output=avail,pcent / | tail -1'
& $a 'sudo -n du -sh "$M2" 2>/dev/null | sed ''s/^/  maven cache /'''
& $a 'echo "PLUGIN BUILT AND INSTALLED"'
& $a 'echo "=== END ==="'

Set-Content -LiteralPath (Join-Path $repo 'scripts\remote\build-plugin.sh') -Value $o -Encoding UTF8

# ---- the config deployer, with the template inlined -------------------------
$tplPath = Join-Path $repo 'scripts\remote\deploy-plugin-config.template.sh'
if (-not (Test-Path -LiteralPath $tplPath)) { throw "Missing $tplPath" }
$cfgLines = Get-Content -LiteralPath (Join-Path $pluginDir 'src\main\resources\config.yml')
$d = New-Object System.Collections.Generic.List[string]
$d.Add('# deploy-plugin-config.sh - GENERATED by scripts/gen-build-plugin.ps1 from')
$d.Add('# deploy-plugin-config.template.sh and plugin/src/main/resources/config.yml.')
$d.Add('# Do not edit by hand.')
foreach ($line in (Get-Content -LiteralPath $tplPath)) {
  if ($line.Trim() -eq '__CONFIG_TEMPLATE__') {
    foreach ($c in $cfgLines) { $d.Add($c) }
  } else {
    $d.Add($line)
  }
}
Set-Content -LiteralPath (Join-Path $repo 'scripts\remote\deploy-plugin-config.sh') -Value $d -Encoding UTF8

Write-Output ("wrote scripts/remote/build-plugin.sh (LaughTail {0}, {1} source files)" -f $version, $files.Count)
Write-Output 'wrote scripts/remote/deploy-plugin-config.sh'
