# gen-fetch-artefacts.ps1 - reads server/manifest.yml and emits a bash script that
# downloads each pinned artefact ON THE HOST and verifies it against the
# publisher checksum there.
#
# Why host-side: the VPS has better bandwidth than the build PC, and it means the
# bytes that get installed are the bytes that were verified - no upload step in
# between where something could differ. Never-break rule 9.
#
# The generated script is committed so it is reviewable, and it refuses to
# install anything whose checksum does not match. Fail closed.

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$man  = Join-Path $repo 'server\manifest.yml'
$dest = Join-Path $repo 'scripts\remote\fetch-artefacts.sh'

$components = @()
$cur = $null
foreach ($line in Get-Content -LiteralPath $man) {
  if ($line -match '^\s*#') { continue }
  if ($line -match '^\s{2}-\s+name:\s*"(.+)"\s*$') {
    if ($cur) { $components += $cur }
    $cur = [ordered]@{ name = $Matches[1] }
    continue
  }
  if ($null -ne $cur -and $line -match '^\s{4}(\w+):\s*"(.*)"\s*$') { $cur[$Matches[1]] = $Matches[2] }
}
if ($cur) { $components += $cur }
$components = @($components | Where-Object { $_.url })

$mcVersion = (Select-String -LiteralPath $man -Pattern '^minecraft_version:\s*"(.+)"' ).Matches[0].Groups[1].Value

$o = New-Object System.Collections.Generic.List[string]
$o.Add('# fetch-artefacts.sh - GENERATED by scripts/gen-fetch-artefacts.ps1')
$o.Add('# Do not edit by hand. Regenerate from server/manifest.yml.')
$o.Add(("# Minecraft {0}. Every checksum below is publisher-stated." -f $mcVersion))
$o.Add('#')
$o.Add('# Downloads into a staging directory. Installs nothing. Verifies everything.')
$o.Add('')
$o.Add('STAGE=/home/ubuntu/laughtail-stage')
$o.Add('mkdir -p "$STAGE"')
$o.Add('cd "$STAGE"')
$o.Add('FAIL=0')
$o.Add('')

foreach ($c in $components) {
  $tool = if ($c.checksum_algo -eq 'sha256') { 'sha256sum' } else { 'sha512sum' }
  $o.Add(('# ---- {0} {1} ----' -f $c.name, $c.version))
  $o.Add(('EXPECT="{0}"' -f $c.checksum.ToLowerInvariant()))
  $o.Add(('FILE="{0}"' -f $c.file))
  $o.Add('if [ -f "$FILE" ] && [ "$(' + $tool + ' "$FILE" | cut -d" " -f1)" = "$EXPECT" ]; then')
  $o.Add(('  echo "  cached+verified {0}  $FILE"' -f $c.name))
  $o.Add('else')
  $o.Add(('  echo "  downloading {0}  $FILE"' -f $c.name))
  $o.Add(('  curl -sSL --retry 3 --retry-delay 2 -o "$FILE" "{0}"' -f $c.url))
  $o.Add('  ACTUAL="$(' + $tool + ' "$FILE" | cut -d" " -f1)"')
  $o.Add('  if [ "$ACTUAL" = "$EXPECT" ]; then')
  $o.Add(('    echo "  OK   {0}  {1} verified"' -f $c.name, $c.checksum_algo))
  $o.Add('  else')
  $o.Add(('    echo "  FAIL {0}  {1} MISMATCH"' -f $c.name, $c.checksum_algo))
  $o.Add('    echo "       expected $EXPECT"')
  $o.Add('    echo "       actual   $ACTUAL"')
  $o.Add('    rm -f "$FILE"')
  $o.Add('    FAIL=$((FAIL+1))')
  $o.Add('  fi')
  $o.Add('fi')
  $o.Add('')
}

$o.Add('echo "=== staged files ==="')
$o.Add('ls -lh "$STAGE"')
$o.Add('echo "=== disk ==="')
$o.Add('df -h --output=avail / | tail -1')
$o.Add('echo "failures: $FAIL"')
$o.Add('if [ "$FAIL" -ne 0 ]; then echo "ARTEFACT FETCH FAILED - installing nothing"; exit 1; fi')
$o.Add('echo "ALL ARTEFACTS VERIFIED ON HOST"')

Set-Content -LiteralPath $dest -Value $o -Encoding UTF8
Write-Output ("wrote {0} ({1} lines) for {2} components, MC {3}" -f 'scripts/remote/fetch-artefacts.sh', $o.Count, $components.Count, $mcVersion)
